### ISSUE TITLE
Use the view macro for better readability

### ISSUE THREAD

**Issue by AaronErhardt** [pop-os/cosmic-settings#1]
Out of curiosity, I had a look at the code and noticed a lot of the code like this:
https://github.com/pop-os/cosmic-settings/blob/master/src/ui/section.rs#L17

Even when using cascade it doesn't look very nice (at least to me) and the structure of the UI is somewhat hidden. With Relm4's view macro (that's even independent from Relm4 itself with the upcoming release), the code I've linked (line 17 to 37) would look roughly like this:

```rust
view! {
    row = ListBoxSelectionRow::new(S::NAME.into()) {
        add_css_class: "nav-element",
        set_margin_all: 8,
        set_child: entry_box = Some(&gtk4::Box) {
            set_orientation: Orientation::Horizontal,
            set_spacing: 8,
            set_margin_all: 10,
            append: icon = &Image::from_icon_name(Some(S::ICON)) {},
            append: label = Label {
                set_label: S::NAME
            }
        }
    }
}	
```

**Comment by AaronErhardt** [comment]
Not with the current stable version but with the upcoming release that will shortly follow gtk4-rs v0.4 it will. It then only requires `relm4-macros` which doesn't need `relm4` as dependency.

**Comment by Absolucy** [comment]
Alright, cool! Thanks!

**Comment by AaronErhardt** [comment]
Version 0.4 is stable now: https://aaronerhardt.github.io/blog/posts/announcing_relm4_v0.4/

**Comment by Absolucy** [comment]
Done :)
