### ISSUE TITLE
(Settings) Scrolling Not Functioning.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-settings#113]
When attempting to scroll with either a scroll-wheel or two-finger scrolling, scrolling down is intermittent and scrolling up does not appear to work.

It also appears that scroll right works, but scroll left does not. This is visible with the `Accent color` options in `settings/desktop/appearance`

I am not sure if this worked prior to the latest changes to Cosmic-settings, but I do not recall problems with it, leading me to suspect this might be a regression.

**Comment by mmstick** [comment]
May be a cosmic-comp update. Scrolling with the latest version until I rebooted into the most recent cosmic-comp version.

**Comment by wash2** [comment]
Do you only notice the issue on the appearance page? I think the scroll bar widget for the accent colors might prevent the pages scroll bar from receiving the scroll events if your cursor is over the accents

**Comment by ids1024** [comment]
https://github.com/pop-os/cosmic-comp/pull/241 did change how scrolling works in the compositor, so it's possible there's an issue there, or something Iced isn't handling correctly.

**Comment by XV-02** [comment]
> Do you only notice the issue on the appearance page? I think the scroll bar widget for the accent colors might prevent the page's scroll bar from receiving the scroll events if your cursor is over the accents

I initially saw the scroll problem on the `wallpaper` page. It seems to effect `settings` broadly. 


It sounds like folks are suspecting this is tied to a compositor update. Should I move this issue to the cosmic-comp repo, or is this a fix that needs to be implemented in cosmic-settings?

**Comment by mmstick** [comment]
I think the source of the problem would be in the sctk runtime in pop-os/iced somewhere.

**Comment by ids1024** [comment]
Hm I thought I tested the `axis_discrete` logic in https://github.com/Smithay/smithay/pull/1246, but it looks like it may not be working correctly. That may be the issue here.

**Comment by ids1024** [comment]
Yeah, looks like there where a couple small issues in my logic there: https://github.com/Smithay/smithay/pull/1252

**Comment by gabriele2000** [comment]
By the way since almost a week everything works again, at least for me.
