### ISSUE TITLE
Wallpaper Wrap-Up List

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#114]
- [ ] When slideshow is toggled on, start from the currently active wallpaper (rather than the first wallpaper in the list)
- [ ] When Slideshow is toggled off, stay on the currently active wallpaper (rather than switching to the first wallpaper in the list)
- [ ] Background fit: remove "Stretch:
- [ ] Background fit: rename "Zoom" to "Fill"
- [ ] Always default to "Fill"
- [ ] Change  the display selector from segmented control to the tabs widget (reasoning: tabs are like switching a page where settings inside the tab are applicable only to the selected tab - in this case, wallpaper on the display)
- [ ] Wishlist - can we fade between wallpaper selections? Currently there's a flash to a dark background then to the wallpaper.
- [ ] Wallpaper per display - clicking the second display flips the backgrounds (tested with two displays)
To reproduce: set a different background for two displays. Click between the displays. The wallpaper flips on the display each time.

**Comment by Archprogrammer** [comment]
Sorry, for commenting late in the process, but does wallpaper per display also include wallpaper per workspace or is it only actual screens?

**Comment by mmstick** [comment]
@Archprogrammer The `cosmic-bg` daemon only supports per-display wallpaper handling right now. It could be possible to support workspaces eventually.
