### ISSUE TITLE
Settings > Region and Language

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#12]
Implement without "Advanced Formatting" for MVP. Limitations with how Linux stores formats requires revisiting advanced formatting possible options.

-- Carl

**Comment by maria-komarova** [comment]
Mockups and other notes are in [this file](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=609%3A25720).

**Comment by WatchMkr** [comment]
Implement without "Advanced Formatting" for MVP. Limitations with how Linux stores formats requires revisiting advanced formatting possible options.

**Comment by maria-komarova** [comment]
Updated designs for Region & Language panel ([Figma file with more details](https://www.figma.com/design/Z6Z9Ox6WNkiiM8gcAkcElS/COSMIC-Settings-First-Release---Developer-Handoff?node-id=13840-35565&t=eofarm6n1EzumKaA-1)):
![Region and Language](https://github.com/user-attachments/assets/58c1b676-65fa-42cb-9fe3-55b1b85f5434)

**Comment by ikeycode** [comment]
Quite happy if you guys wanna lift anything from https://github.com/serpent-os/lichen/tree/main/crates/system/src/locale - which provides `gnome-desktop` compatible region & language grouping + parsing.

**Comment by anaTropeas** [comment]
Is there a case for changing keyboard input layout for those who have 2 languages because the keyboard shortcut is not working ? Or if there is a config file to change from terminal that we can set a keyboard layout change shortcut key combination as ALT+SHIFT or whatever?

**Comment by maria-komarova** [comment]
We need to add the shortcut, not sure why we don't yet have it in Keyboard shortcuts settings. But one can also change the layout via the applet on the Panel (usually shows the abbreviation for the current layout, for example, US.

**Comment by Sporesirius** [comment]
Hi, wouldn't it make more sense to use radio buttons for settings with only a few options (e.g., three or fewer like Temperature or Measurement)? Right now, the layout feels a bit empty.

**Comment by maria-komarova** [comment]
> Hi, wouldn't it make more sense to use radio buttons for settings with only a few options (e.g., three or fewer like Temperature or Measurement)? Right now, the layout feels a bit empty—could this be due to responsiveness?

We're not doing the granular settings like that because of the limitations mentioned above (those would fall under Advanced formatting).
