### ISSUE TITLE
(Settings/Desktop/Appearance) Color picker window size and scroll bar issues

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-settings#125]
I noticed that there are two small issues related to the default size of the color picker as it is spawned in floating-window mode.

The first is the default height of the window. When spawned, the default height is adequate to display the entire color picker interface only if the `Recent Colors` element is not present. If a color picker has been adjusted, so the `Recent Colors` element is present, then the `Reset to default button` will be largely forced out of view. I also noted that the color picker does not have a vertical scrollbar when this happens. Compare the top image, without the `Recent Colors` element, to the lower:
![Screenshot_2024-01-16_10-43-25](https://github.com/pop-os/cosmic-settings/assets/98765732/28845c36-b2d7-426e-abff-2fec0ee0ac94)
![Screenshot_2024-01-16_10-44-15](https://github.com/pop-os/cosmic-settings/assets/98765732/151c28b9-a9f0-4476-8895-c0d910f1cae6)

Additionally, if enough colours have been selected that the `Recent Colors` element requires a horizontal scrollbar, while the scrollbar appears, it is drawn in over the element itself: 
![Screenshot_2024-01-16_12-17-45](https://github.com/pop-os/cosmic-settings/assets/98765732/86d70afe-0833-40c1-80d7-4153f927640d)

And, lastly, I noted that, when I adjust the horizontal width of the color picker window when the `Recent Colors` element was present, that the height of the window also adjusted itself:
![Screenshot_2024-01-16_10-44-56](https://github.com/pop-os/cosmic-settings/assets/98765732/941314b4-f0cb-497e-9904-0aef0e0fc211)
The window in this screenshot has had it's width increased manually by a few pixels. The window "self adjusted" its height by about 50 pixels, allowing all elements to be presented.

Adjusting the height doesn't resolve the issue with the horizontal scrollbar drawing over the `Recent Colors` element.

I've included both aspects, as they seem to be tied directly to how the window is drawn. The height issue is interesting to me; the fact that a vertical scrollbar doesn't appear, but that the window increases height to adequately show all elements when I independently adjust the width of the window makes me feel like somewhere in the background, the desired change in window size has been registered, but not actually executed.

But, given that the horizontal scrollbar appears not to draw correctly, I do also wonder if there is a vertical scrollbar, but it isn't being rendered correctly.

**Comment by wash2** [comment]
Ya, there needs to be a libcosmic scrollbar implementation at some point. The iced scrollbar widget is overlayed on top of content. The button being shrunk is probably a quirk with the autosized surface being slightly smaller than the application actually requires. Maybe this is a rounding error in iced-sctk.
