### ISSUE TITLE
Can't add two applets to the panel in a row

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-settings#129]
Version: 039aeb1

After adding an applet to the panel, the `Add Applet` button remains greyed out until the Settings app is closed/relaunched.

![screenshot-2024-01-29-17-00-12](https://github.com/pop-os/cosmic-settings/assets/7199422/555a02dd-9258-4f69-b6b4-a852f1ab2efb)

**Comment by leb-kuchen** [comment]
![screenshot-2024-02-13-16-24-57](https://github.com/pop-os/cosmic-settings/assets/102472435/40683b2c-306d-4b25-a833-4491e8f70b08)
Adding a applet does not stop the existing ones.

**Comment by leviport** [comment]
@leb-kuchen the bug isn't the apps crashing or halting. It's that the "Add Applet" button becomes inactive until settings is closed and reopened.

**Comment by leb-kuchen** [comment]
I though it might be related to

**Comment by jacobgkau** [comment]
@leb-kuchen That doesn't sound directly related to this issue, but it does sound like something that should be reported as a separate issue.
