### ISSUE TITLE
Settings > About

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#13]

**Comment by maria-komarova** [comment]
The About panel in COSMIC Settings is where users can find the information about their OS and hardware.


![About](https://user-images.githubusercontent.com/57502897/211647117-c41708ba-ff42-4ebc-b011-cc6c2c968bf1.png)

![renaming-device](https://user-images.githubusercontent.com/57502897/211647656-1988e7ef-ec3a-423d-b76c-4b3b90410289.gif)

The biggest difference is the use of the compact input inside the ListItem for renaming the device and the addition of the Related Settings section.

**Comment by qaqak** [comment]
The word "bluetooth" should be changed to "Bluetooth" as it is a proper noun and the name of a connection protocol.

**Comment by User8395** [comment]
Goddam this is old
