### ISSUE TITLE
[Displays] Scrollbar/extra space appears in display layout even with only one display

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-settings#136]
Version: d943b5b

On the Displays page, when there's only one display present, a horizontal scrollbar appears under the display layout area (and I'm able to scroll) even though there's plenty of empty space around the only display and there should be no need to scroll.

![screenshot-2024-02-01-18-05-33](https://github.com/pop-os/cosmic-settings/assets/7199422/ef66791c-d9db-4ef3-ae0a-9ca83d7b7c8c)

![screenshot-2024-02-01-18-07-35](https://github.com/pop-os/cosmic-settings/assets/7199422/be89e01a-1fd9-43a9-8dd6-551cdb1096e8)

**Comment by WatchMkr** [comment]
I can reproduce this by unplugging a second display while on the Displays settings page.
