### ISSUE TITLE
Displays > Add mirroring options from design

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#145]
Requires https://github.com/pop-os/cosmic-comp/issues/302 which is slated for post-alpha

Designs https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?type=design&node-id=693-63625&mode=design&t=4k2fMYy6NnkaoRYm-0

**Comment by gantryyork** [comment]
I'd recommend the following modes

- Join/extend
- Mirror
- Single (with laptop)

**Comment by JamesClarke7283** [comment]
In the meantime, is there a way i can mirror one screen onto another manually in cosmic-epoch?
maybe a config or command?

**Comment by mmstick** [comment]
@JamesClarke7283 You can use cosmic-randr

**Comment by JamesClarke7283** [comment]
> @JamesClarke7283 You can use cosmic-randr

I tried. It did not work. Can you give the exact command?

**Comment by mmstick** [comment]
`cosmic-randr mirror <OUTPUT> <FROM>`

**Comment by WatchMkr** [comment]
The cosmic-comp portion has been completed so we can add this after keyboard shortcuts work is complete.
