### ISSUE TITLE
Display : can not apply 165hz

### ISSUE THREAD

**Issue by ryzendew** [pop-os/cosmic-settings#157]
my monitor is 2560x1440 and 1920x1080 and both are 165hz and i can't apply 165hz but can apply 144hz  both monitors are display port.
also turning off displays does not work

**Comment by mmstick** [comment]
Is it listed as an available option from the wlr display protocol? You can list available modes with `cosmic-randr list`.

**Comment by RyzenDew** [comment]
> Is it listed as an available option from the wlr display protocol? You can list available modes with `cosmic-randr list`.

yes and cosmic DE is the only DE with this issue

**Comment by RyzenDew** [comment]
newest cosmic compiled today and still an issue

**Comment by Schweeeeeeeeeeeeeeee** [comment]
for me its still an issue and has been since alpha 1 i think

**Comment by mmstick** [comment]
@Schweeeeeeeeeeeeeeee Are you using the current git release?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
wanst just alpha 5 imma try the latest git commit tomorrow

**Comment by mmstick** [comment]
There's been a lot of cosmic-comp improvements since the tagged release, so it's most likely fixed now.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Sorry for the delay 
I installed the cosmic-git package on arch but not i cant even open my cosmic apps the desktop works but setting any resolution i wouldnt know how to do :(
