### ISSUE TITLE
Settings > Wallpapers

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#16]

**Comment by maria-komarova** [comment]
The Wallpaper panel in COSMIC Settings is where users can choose a background image and a color for their displays, or set the background to cycle through the slideshow.

![Wallpaper-defaults](https://user-images.githubusercontent.com/57502897/211648508-44f0f534-615b-4448-af1f-051bb0805361.png)

### Background options
The panel provides an ability to choose a background from:
- System backgrounds (a set of images that comes with the system)
- Colors (a set of solid colors that could be deleted or added)
- A folder from the Files system on the device that a user can open through the Files application.
Any of these sets of backgrounds could be toggled to a slideshow.

![background options](https://user-images.githubusercontent.com/57502897/211649493-adb0d8f8-6024-41d6-b840-d209200e13fb.gif)

There is also a button to add image/color available. After clicking the button and either choosing an individual image from the Files or selecting a color from the color picker, it is immediately applied as the background and added as the first item in the grid with the selected state. For System backgrounds, only images the user adds intentionally are the ones that can be removed. 

![delete-added-image](https://user-images.githubusercontent.com/57502897/211649884-d57c4c8a-f481-45aa-9a85-d7b09f0523f7.gif)
The mockup above shows wallpaper panel after an image has been added and is now deleted.  

### Slideshow
When Slideshow is toggled on, there is an additional List Item with the dropdown for setting the time when the image should change. Options include 5 minutes, 10 minutes, 15 minutes, 30 minutes, 1 hour, 2 hours. All the images become available for multiple selection - one can add/remove them from the slides how by clicking/tapping on them. 

![slideshow](https://user-images.githubusercontent.com/57502897/211651504-ae033c12-5585-4e10-b6a2-e21b975ea14f.gif)


### Setting different wallpaper per display
The mockups include a function to set different wallpaper on each display. Un-toggling “Same background on all displays” enables tabs for each display that allow setting different backgrounds. 

![different-per-display](https://user-images.githubusercontent.com/57502897/211652182-eb640a19-1524-4a80-8b92-d203c5df31ef.gif)

**Comment by Sporesirius** [comment]
First of all, many thanks to the whole Pop OS team for all their hard work. It looks really good.

Will animated wallpapers also be supported?

**Comment by bluthej** [comment]
Very excited about the new DE!

One thing that I have learned to love while using Sway as my WM is to have a wallpaper picked at random whenever the WM is started. It's super easy to do.
There are some python and bash scripts that replicate that behavior in other environments but it would be nice to have that as an option in the settings :)
Just putting it out there

**Comment by Macdhai** [comment]
For the slideshow wallpaper feature, will users e able to add additional folders to pull from, or will they be restricted to files in the default backgrounds folder?

**Comment by WatchMkr** [comment]
Checklist to match design features and functions:

- [ ] Bug: Wallpaper panel scrolls infinitely
- [ ] Add selected indicator to the bottom left of thee selected background image
- [ ] "Add image" text label and open file chooser/add image for System backgrounds
- [ ] Ability to delete the added image (@maria-komarova probably should be the trash icon instead of X for close)
- [ ] "Add color" text label and open color picker for Colors
- [ ] Ability to delete the added color (probably should be the trash icon instead of X for close)
- [ ] When Slideshow is active, add select boxes to the images (all images selected by default)
- [ ] Retain selected backgrounds state when Slideshow is toggled off 

The feature to add a system folder will be held for post-release.

**Comment by maria-komarova** [comment]
One more thing - the design uses tabs for switching the view between the displays rather than the segmented control/button. This is more consistent with other instances in the designs, for example, on the Displays panel.

**Comment by WatchMkr** [comment]
Feature wrap-up list here: closing.
