### ISSUE TITLE
Desktop and Panel > ListItems to choose the panel or dock are messed up

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#171]
![screenshot-2024-02-29-22-57-46](https://github.com/pop-os/cosmic-settings/assets/3430283/dcf128d5-7008-4727-b1ae-1a53ecc91a28)
![screenshot-2024-02-29-22-59-02](https://github.com/pop-os/cosmic-settings/assets/3430283/6a643d45-e349-4afd-8208-a12ecf7db296)

**Comment by mmstick** [comment]
Fixed by 7e851fe
