### ISSUE TITLE
Desktop > Appearance: Disable color mode switcher when automatic mode switch is enabled.

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/cosmic-settings#177]
I encountered an inconsistency with the color mode switcher in the Settings app:

When the "Automatic mode switch" is enabled, the color mode switcher remains functional.

This behavior can be confusing because the mode change only applies within the Settings app itself, not the entire desktop environment.

![screenshot-2024-03-06-13-50-34](https://github.com/pop-os/cosmic-settings/assets/22224438/53b2380a-27f4-4a67-a719-badf9f57882c)

## Steps to reproduce:

- Enable the "Automatic mode switch" in the Settings app.
- Observe that the color mode switcher is still active.
- Switch the color mode.
- Notice that the color change only affects the Settings app, not the rest of the desktop.

## Expected 

Either:
- The color mode switcher is disabled when the "Automatic mode switch" is enabled.
- A clear message is displayed informing users that the color mode switcher only affects the Settings app when the "Automatic mode switch" is active.

## Additional information:

I am happy to contribute a pull request to implement the suggested solution, if it aligns with the project's direction.

Please let me know your thoughts.

**Comment by wash2** [comment]
The intent of keeping the switcher active is to allow users to customize both light and dark mode when auto-switching is active. I guess it could be stopped from setting the theme, but then I don't know if the user would be able to see any effects of changes they make.

**Comment by edfloreshz** [comment]
Another alternative would be to disable the switch if the user overrides the mode manually after enabling the auto-switch, a warning could be presented to let them know the auto-switch will be disabled.

I thought it was a bug before realizing I had the switch enabled.

**Comment by WatchMkr** [comment]
@wash2 The user should be able to override the mode using the switcher even when "automatically switch..." is active.

The helper text under "automatically switch..." should change depending on the state.

Helper text:

Light mode helper text during the day
- Switches to Dark mode at sunset

Dark mode helper text at night
- Switches to Light mode at sunrise

Light mode overridden to dark by the user at day
- Switches to dark mode at the next sunset

Dark mode overridden to light by the user at night
- Switches to light mode at the next sunrise

**Comment by wash2** [comment]
Ok, I'll make the adjustments today 👍
