### ISSUE TITLE
Settings > Input Devices > Touchpad: Left "primary button" button does not render text correctly on scaled displays

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-settings#178]
![screenshot-2024-03-06-19-24-13-inset](https://github.com/pop-os/cosmic-settings/assets/98765732/94c354bb-7ca4-4b67-9f72-a7af37dde5fb)

As can be seen, the "Left" button for the `Primary button` selection does not render correctly. This happens when you enter the Touchpad settings page on a scaled display at certain scales. You do not need "Left" selected to trigger this bug

This happens on the default themes (dark and light) as well as my customized theme. 

This happens on displays when scaling up or down. I saw issues at 75%, 125%, and 150% scaling, but not at 50%. The display tested has a native 1920x1080 resolution. 

It seems to get correctly rendered if you interact with any other item within the settings pane itself, when you click out of the window, and briefly when the screenshot tool is first launched (though this obviously doesn't persist).

It appears to get re-broken when ever you interact in any way shape or form with the settings draw on the left hand side of the settings application. 

It does not effect the same button on the settings page for mice.

**Comment by mmstick** [comment]
This may be a rendering artifact with our software renderer in iced. I will eventually switch to wgpu once I fix a rendering issue with a widget there.

**Comment by mmstick** [comment]
Fixed by https://github.com/pop-os/libcosmic/pull/330
