### ISSUE TITLE
Is the use of `css-classes` intentional?

### ISSUE THREAD

**Issue by BrainBlasted** [pop-os/cosmic-settings#18]
https://github.com/pop-os/cosmic-settings/blob/b3ebe0f61b4095dfb8e75c52d0feffb3c6da636d/src/widgets/search_bar.rs#L63

In GTK4, `css-classes` wipes out all other CSS classes on a widget when set, including the default ones. Depending on the widget this can completely break styling unless your styling substitutes it properly. Is this intentional?

If not, you should be using `add_css_class()`/`remove_css_class()`.

**Comment by mmstick** [comment]
The code here is outdated. I haven't yet synced the changes I've done in a refactor to relm4.
