### ISSUE TITLE
Settings > Input Devices > Keyboard: Opening both Alternate Characters and Compose Key dialogs and then closing one causes the wrong one to close, and the remaining one to become unresponsive

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-settings#184]
Happens both in tiling mode and floating mode, but looks more broken in tiling mode. Presumably this is because the tiler is resizing a dialog that's in a "stuck" state.

To recreate:
- Open Cosmic Settings and navigate to the Keyboard page
- Open Compose dialog and Alternate Keys dialog (order doesn't seem to matter):
![screenshot-2024-03-07-17-48-02](https://github.com/pop-os/cosmic-settings/assets/13512097/1e39b6f7-ebcb-42f4-af2d-1bedf96bbe2e)
- Now close one of the dialogs:
![screenshot-2024-03-07-17-48-14](https://github.com/pop-os/cosmic-settings/assets/13512097/475ebfd3-04a4-4875-83b1-fd38d1613d07)
- The remaining dialog will look broken and become unresponsive to input, but can still be closed with Super + Q

In floating mode, if I open both dialogs like this:
![screenshot-2024-03-07-17-48-43](https://github.com/pop-os/cosmic-settings/assets/13512097/c773eaa0-eb9b-4bc8-a973-ee9692f4796f)

Clicking the X button on the Compose dialog causes the Alternate Characters dialog behind it to close, and the Compose dialog becomes unresponsive:
![screenshot-2024-03-07-17-48-53](https://github.com/pop-os/cosmic-settings/assets/13512097/458c0364-6871-4a73-84a7-7aee8da398bd)

Also, I'm not sure if this should be a separate issue, but I noticed that I can open multiple instances of the same of either of these dialogs by clicking the button more than once. I would normally expect only being able to open one, and any clicks while the one is open to focus the already-open dialog. I can open a separate issue for this if needed, but it did seem related.

**Comment by WatchMkr** [comment]
Should be resolved now that they're in the ContextDrawer.
