### ISSUE TITLE
Question: How to add settings pages or sections?

### ISSUE THREAD

**Issue by leb-kuchen** [pop-os/cosmic-settings#185]
A blog post mentioned, you would be able to  add or remove settings pages. 
So my question is if is already implemented and how, e.g. an apple would be able to do so?

**Comment by mmstick** [comment]
The source code is open so you can compare the existing pages that have already been implemented.

**Comment by leb-kuchen** [comment]
https://blog.system76.com/post/may-flowers-spring-cosmic-showers
The blog post mentions an API for that.

**Comment by mmstick** [comment]
It's an internal API in this project, used by its own pages. Here are a few page modules

- [About](https://github.com/pop-os/cosmic-settings/blob/master/app/src/pages/system/about.rs)
- [Touchpad](https://github.com/pop-os/cosmic-settings/blob/master/app/src/pages/input/touchpad.rs)
- [Wallpaper](https://github.com/pop-os/cosmic-settings/blob/master/app/src/pages/desktop/wallpaper/mod.rs)
- [Appearance](https://github.com/pop-os/cosmic-settings/blob/master/app/src/pages/desktop/appearance.rs)

The [Desktop page](https://github.com/pop-os/cosmic-settings/blob/71cfd2d2f0b3dcde64c74eb4faf6af4d82c62fd3/app/src/pages/desktop/mod.rs#L49) is a category that defines a list of sub-pages.

You can see top level pages inserted into the application [here](https://github.com/pop-os/cosmic-settings/blob/71cfd2d2f0b3dcde64c74eb4faf6af4d82c62fd3/app/src/app.rs#L112).

**Comment by leb-kuchen** [comment]
This is kind of what I meant, or it is needed to change settings pages?
  ``` crate::pages::Message::External { .. } => {
                    todo!("external plugins not supported yet");
                }
```

**Comment by mmstick** [comment]
That has never been supported, and it is unclear if it will ever be supported.

**Comment by leb-kuchen** [comment]
What is described in the blog is not implemented.
Thank you for taking the time and answering my questions.
