### ISSUE TITLE
Settings > Desktop > Appearance: "Reset to default" button while on light theme resets light theme to dark theme defaults

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-settings#196]
To recreate: 
- Select light mode
- Click "reset to default" button at the bottom

Behavior:
Default dark theme is loaded

Expected: 
Default light theme would be loaded

Version:
```
cosmic-settings:
  Installed: 0.1.0~1709923903~22.04~0629042
  Candidate: 0.1.0~1710285950~22.04~d6b2823
  Version table:
     0.1.0~1710285950~22.04~d6b2823 1002
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
     0.1.0~1709933643~22.04~65289d9 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 0.1.0~1709923903~22.04~0629042 100
        100 /var/lib/dpkg/status
```

**Comment by wash2** [comment]
Have you tested with one of the recent commits? When I test with latest master, it correctly resets to the light theme, but using the commit you are on, it does not.

**Comment by leviport** [comment]
Sorry, I forgot to re-test this after reading your message. I've re-tested now, and resetting the light theme does indeed reset it to the light theme defaults as expected.
