### ISSUE TITLE
Settings > Appearance > Dark/Light and Style no selected state outline

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#198]
Here "Dark" is selected but there is no outline showing it's selected.

![screenshot-2024-03-15-18-18-08](https://github.com/pop-os/cosmic-settings/assets/3430283/9d2d28cd-c357-47c5-8fdf-c3c82ed18a32)

Here "Round" is selected but there is no outline showing it's selected.

![screenshot-2024-03-15-18-16-36](https://github.com/pop-os/cosmic-settings/assets/3430283/835e9b2d-d5d8-4d57-bc72-5678f107bc71)

**Comment by wash2** [comment]
should be fixed by #207
