### ISSUE TITLE
[major issue] this is the ugliest thing I have ever seen in my life

### ISSUE THREAD

**Issue by clydebottoms** [pop-os/cosmic-settings#2]
Fire literally everyone who made this and delete the repo, now.

**Comment by Absolucy** [comment]
haha funne shitpost

**Comment by clydebottoms** [comment]
not a shitpost this is fucking disgusting, almost as bad looking as garuda, please delete the custom css you added and take a ui design class.

**Comment by Absolucy** [comment]
For future reference: constructive criticism is best. Say precisely what's wrong, and _how_ it could be done better. Just saying "this is fucking disgusting" helps nobody.
