### ISSUE TITLE
Add icon themes previews to menu screen

### ISSUE THREAD

**Issue by TheESN** [pop-os/cosmic-settings#208]
![main](https://github.com/pop-os/cosmic-settings/assets/102585253/846083af-fa1e-47d8-9cb9-3156b6b73b4e)

I suggest to make something like in KDE Plasma to make it more clear to user what exactly icons they want to choose

**Comment by joshuamegnauth54** [comment]
I implemented a feature in the linked PR that seems _sort of_ like this.

**Comment by maria-komarova** [comment]
#235 should describe the design for the feature that should address this issue once implemented.
