### ISSUE TITLE
Settings > Desktop > Wallpaper: Missing preview and outline of current wallpaper

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-settings#211]
When the wallpaper is changed, the preview on the top and the outline with the checkmark on the image are visible:
![screenshot-2024-03-22-15-48-55](https://github.com/pop-os/cosmic-settings/assets/150025636/fc4bc1a6-c327-4517-a8db-744627c5ca15)
If going back from the Wallpaper page and then returning, the outline is missing. Closing Settings and reopening leads to the preview being black, as well.
![screenshot-2024-03-22-15-49-20](https://github.com/pop-os/cosmic-settings/assets/150025636/4ca4db04-b91d-423e-a391-2ed666cda544)

**Comment by WatchMkr** [comment]
This appears to be fixed.

**Comment by git-f0x** [comment]
It's still present for me, unless the latest commit which hasn't yet been pushed to apt fixed it.

**Comment by edfloreshz** [comment]
I cannot reproduce this.

**Comment by git-f0x** [comment]
Why do I always have weird issues... 🫠

**Comment by WatchMkr** [comment]
Just had this happen on an AMD graphics system.

**Comment by edfloreshz** [comment]
Which steps did you take to reproduce it?

**Comment by git-f0x** [comment]
Since I am on AMD graphics, this issue might be related to pop-os/libcosmic#370 , since it also seems to occur on AMD graphics there.

**Comment by git-f0x** [comment]
> Which steps did you take to reproduce it?
For me just opening the Wallpaper page in Settings.

**Comment by git-f0x** [comment]
I seem to have figured out when this happens (at least on my end).
When there is an added image for wallpapers, wallpaper settings don't exhibit this issue.
When there are no added wallpapers, the issue occurs every time.

**Comment by git-f0x** [comment]
This may or may not be related to this: when there's an added wallpaper, it isn't present when the Wallpaper page is first opened. It appears only when something is hovered over, or the window is moved or scrolled.

https://github.com/pop-os/cosmic-settings/assets/150025636/a8fe2a55-b1f7-4bc5-87e7-c9b300abe2fe

**Comment by gantryyork** [comment]
New wallpapers will not be part of the Alpha-Release?

**Comment by joshuamegnauth54** [comment]
Good news, everyone!

I may have fixed this issue. I am able to replicate the problem 100% of the time using the instructions @git-f0x posted above. Let me know in the PR if the patch worked for those who experienced the issue or else I can try further to fix it.

**Comment by git-f0x** [comment]
That seems to fix the issue!
It doesn't fix the issue in the recording above, and when a non-default/added wallpaper is the current wallpaper, it seems to also make the preview blank (for the added wallpaper) until the actions mentioned above are performed (so that PR changes that issue somewhat).
But that doesn't seem to be related to this issue.
