### ISSUE TITLE
Searchable pages clutter application library

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-settings#218]
Since https://github.com/pop-os/cosmic-settings/commit/1c618854283e036b144b6281d442e8e5d1dc1bdb, while all desktop files are searchable with the launcher, they also appear in the application library. 

In particular, all the pages share the same settings icon and appear in the application library's home tab. This significantly clutters the application library. 

In current Pop releases, searchable settings pages do not appear in the application library independently.

**Comment by mmstick** [comment]
This fix was already pushed this morning
