### ISSUE TITLE
Cannot build from parent folder

### ISSUE THREAD

**Issue by golanguage** [pop-os/cosmic-settings#225]
Checkout cosmic-epoch. and get all sub modules, include cosmic-settings.
Run just build from cosmic-epoch.
The result is:

```
...
...
/home/test/.cargo/bin/just cosmic-settings/build-release
cargo build --release 
error: could not find `Cargo.toml` in `/home/test/proj/rust/cosmic-epoch` or any parent directory
error: Recipe `build-debug` failed on line 32 with exit code 101
error: Recipe `build` failed on line 20 with exit code 101

cosmic-epoch>
```

**Comment by mmstick** [comment]
`cd` or `pushd` to cosmic-settings, then run `just`.

**Comment by golanguage** [comment]
> `cd` or `pushd` to cosmic-settings, then run `just`.

Seriously?
Have abandoned the justfile script  of cosmic-epoch?
