### ISSUE TITLE
Bug: No longer installing binary 

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-settings#226]
Commit a8020c5261decaed29e3c503770303df13340f31 broke `just rootdir=$pkgdir install`

You can see the install log messes up the URL to install it to;

> install -Dm0755 /home/quack/code/pkgbuild-scripts/cosmic-epoch/cosmic-settings-git/src/cosmic-settings/target/release/cosmic-settings /home/quack/code/pkgbuild-scripts/cosmic-epoch/cosmic-settings-git/src/cosmic-settings//home/quack/code/pkgbuild-scripts/cosmic-epoch/cosmic-settings-git/pkg/cosmic-settings-git/usr/bin/cosmic-settings

Im not certain. but I think because of installing to the invocation dir `install {{options}} {{ invocation_directory() }}/{{src}} {{ invocation_directory() }}/{{dest}}` it installs to `{{invocation_dir}}/{{root_dir}}`

It's not immediately apparent to me the best way to fix this since im not that familiar with why it was needed in the first place

**Comment by jokeyrhyme** [comment]
It was related to this: https://github.com/pop-os/cosmic-settings/pull/221
