### ISSUE TITLE
touchpad scrolling on settings app very slow compared to other libcosmic apps

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-settings#228]

**Comment by mmstick** [comment]
It is probably because cosmic-settings is using softbuffer instead of wgpu.

**Comment by ryanabx** [comment]
> It is probably because cosmic-settings is using softbuffer instead of wgpu.

Shouldn't they have the same response to libinput? If not, we may need to normalize scroll speed between all the backends in libcosmic

**Comment by WatchMkr** [comment]
@ryanabx Are you still seeing this? The speed seems to be the same now.

**Comment by mmstick** [comment]
cosmic-settings is now using wgpu
