### ISSUE TITLE
Design for additional features to Appearance panel

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#235]
Two new features that have already been added to the Appearance panel were missing the UI. They should be added at the end of the panel under "Experimental settings". Clicking on this list item should open the Context drawer with the toggle to apply current theme to GNOME apps and the ability to select an icon theme. 
The purpose in adding those features under Experimental settings is twofold. They might not work as well as other features. For example, not all icon themes will be designed for being rendered on top of all backgrounds, some icons may be missing or may be misleading. And not all GNOME apps will handle having custom colors set, and any theming issues with those apps should be reported to libcosmic so we can improve our color exporter, not to the apps themselves. Another goal is to reduce the mental overload on Appearance panel that already has a lot of features.

Updated Appearance mockup:
![Appearance-Dark](https://github.com/pop-os/cosmic-settings/assets/57502897/ee2f64da-1a7e-4a8c-9b8a-1604ce22fc63)

Context drawer with Experimental settings:
![ContextDrawer-Experimental-settings](https://github.com/pop-os/cosmic-settings/assets/57502897/01edc605-d500-4c8c-8975-a5870fd2d7d7)
Image buttons should show the render of 6 icons from each theme. The first image button on the mockup has a random selection but it should include the following icons: “folder”, “user-home”, “preferences-system”, “image-x-generic”, “audio-x-generic”, “video-x-generic”.
Image buttons should have a background color @neutral_4.

Image buttons for icon theme selection should use flexible grid layout. Grid layout automatically adjusts the sizing and spacing of the items according to the size of the container available for displaying the items. 

Mockups for the Appearance panel could be found in [this Figma file](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?type=design&node-id=9112%3A1849&mode=design&t=YJCw9jQnxLVi2eOJ-1).

**Comment by senntore** [comment]
Would the interface density settings also apply to Launcher & Application Library?
