### ISSUE TITLE
Cosmic DE Screen Magnifier implementation

### ISSUE THREAD

**Issue by TheBalkanDev** [pop-os/cosmic-settings#24]
Hi,
will Cosmic Develop it's own Screen Magnification Software or will it be using something lime kMag or the GNOME one?

The current issue with Pop!_OS, which I think uses the default GNOME Magnifier, is that it experiences lag and unreliability despite utilizing modern hardware, while simultaneously producing a bit blurry image.

Cosmic Desktop is in its early stages of development and currently, accessibility isn't near a top priority. However, I have high hopes that as the development progresses, the team will create an exceptional version that includes accessibility features. It is exciting to see what the future holds for Cosmic Desktop and I am looking forward to the advancements it will bring.

I'm not sure if I posted it in the right place.

**Comment by TheBalkanDev** [comment]
*like

**Comment by jacobgkau** [comment]
We may want to transfer this issue to https://github.com/pop-os/cosmic-comp?

**Comment by TheBalkanDev** [comment]
Sure

**Comment by TheBalkanDev** [comment]
Should I close it myself

**Comment by jacobgkau** [comment]
We could have transferred it without closing/re-opening, I was just waiting for a developer's opinion.

Linking for future reference: https://github.com/pop-os/cosmic-comp/issues/70

**Comment by TheBalkanDev** [comment]
Thx
