### ISSUE TITLE
Mouse wheel scroll doesn't work in experimental settings panel when it reaches icon themes

### ISSUE THREAD

**Issue by TheESN** [pop-os/cosmic-settings#245]
Mouse wheel stops to work when I reach this part of this panel

![изображение](https://github.com/pop-os/cosmic-settings/assets/102585253/80a540cb-2448-4580-bb99-88c15dfeb19d)

**Comment by XV-02** [comment]
To clarify, which element at you trying to scroll with the mouse wheel:
1) The list of icon sets or
2) The main settings panel for appearance?

**Comment by TheESN** [comment]
> To clarify, which element at you trying to scroll with the mouse wheel:
> 
>     1. The list of icon sets or
> 
>     2. The main settings panel for appearance?

The list of icon sets
