### ISSUE TITLE
[Desktop/Appearance] Accent color field interrupts scroll

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-settings#247]
Scrolling is not possible while the cursor is over the Accent color field (buttons and the "scrollable" field they reside within). This is true both with trackpad scrolling and with a scroll wheel. So far, I haven't found any other button/toggles/interactables which have the same effect. It is particularly noticeable as the Accent color buttons span the majority of the main content area when editing appearance settings. 

I believe it is a result of the horizontally scrollable field in which the Accent colors reside, and it continues to impact the ability to scroll the appearance page vertically even when the settings application is wide enough that the entire Accent color field is visible without needing a scroll bar. I don't know of any other scrollable horizontal field implemented elsewhere against which to test that assumption though.

**Comment by WatchMkr** [comment]
This appears to be fixed.
