### ISSUE TITLE
[Tiling] Sidebar bar does not respond to width of the Settings Window

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-settings#253]
Unlike other Cosmic apps, the sidebar in the Settings app does not hide automatically when we make the width of the window smaller.
Screenshot:
![screenshot-2024-04-30-10-33-45](https://github.com/pop-os/cosmic-settings/assets/58325574/f9fdfe51-3c99-40d9-9bd6-7e97ae7829cd)

**Comment by edfloreshz** [comment]
I cannot replicate this, when I reduce the width it hides the sidebar.

![image](https://github.com/pop-os/cosmic-settings/assets/22224438/a433a3b7-5f64-4b63-b3e1-c40440dabd64)

**Comment by senntore** [comment]
That's strange. I've this issue on version  0.1.0~1714937562~22.04~a544fed of Cosmic Settings.
Here is a recording:
[2024-05-06_1080p_25fps_10pts.webm](https://github.com/pop-os/cosmic-settings/assets/58325574/cd6867f4-aed4-41e9-a53f-c2e7326ff230)

**Comment by git-f0x** [comment]
I believe this is exclusive to tiling.

**Comment by senntore** [comment]
Oh, that explains why @edfloreshz might not have this issue.
Testing again, I found even more issues with the UI in the Settings app.

In floating mode, decrease the width of Settings window to have just the sidebar. If we enter to tiling mode now, the Settings app behave very strangely. As the sidebar does not go back to it's usual state when the width is more than the minimum required for it.

**Comment by WatchMkr** [comment]
Nice catch. So we have two bugs that can be reproduced with:

1. Tile COSMIC Settings and COSMIC Files > Resize windows > Files collapses to the window content, Settings does not
2. Float COSMIC Setting and reduce to a single column. Tile the workspace. The NavBar extended to the entire window width.

**Comment by mmstick** [comment]
Ready to review with commit 4ceac69

**Comment by senntore** [comment]
Yes, these two issues are fixed now. You can close it after testing it in your end.
