### ISSUE TITLE
[Desktop and Panel] Add Super actions options per design

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#274]
Dropdown with:

- Open Launcher
- Open Workspaces
- Open Applications

Instead of "Let Super key" the label should be "Super key action" since left and right Super keys do the same thing.

![screenshot-2024-05-08-23-45-41](https://github.com/pop-os/cosmic-settings/assets/3430283/18576053-661c-4edd-99bd-5881d99fe093)

**Comment by WillyWonksters** [comment]
It is helpful have distinct assignments for left and right super. Left super is used so frequently when switching between apps and workspaces, that I often accidentally open the launcher. I disable this, and now only open the launcher with right super.
