### ISSUE TITLE
[Input Devices > Keyboard] Unable to scroll Special Character Entry ContextDrawers

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#284]
Can't scroll when over the List Items.

![screenshot-2024-05-09-03-27-33](https://github.com/pop-os/cosmic-settings/assets/3430283/1df4c568-add6-4fba-9514-f6283f987dce)

**Comment by git-f0x** [comment]
Also, the Add applets ContextDrawer has the same behavior (and unrelated, the applet rows in the drawer should be a bit wider, to match other ContextDrawers).
