### ISSUE TITLE
[Applets > Add Applet Context Drawer] ListItems are too narrow and aren't scrollable

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#301]
Add Applet ListItems Width
![screenshot-2024-05-09-22-11-27](https://github.com/pop-os/cosmic-settings/assets/3430283/69098486-c1f1-49e5-9aae-20c4c337395f)

Correct ListItem Width
![screenshot-2024-05-09-22-11-59](https://github.com/pop-os/cosmic-settings/assets/3430283/d416b5f8-d16d-4634-b69b-b1c7c7e55121)

**Comment by git-f0x** [comment]
They also aren't scrollable when the cursor is over the list.

**Comment by wash2** [comment]
should be fixed by https://github.com/pop-os/cosmic-settings/commit/1db58f56ccd39d6d64ea47383176fd0d6b9ebeff

**Comment by git-f0x** [comment]
Can confirm, fixed!
