### ISSUE TITLE
Settings > Input Devices > Keyboard > Keyboard Shortcuts

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#32]
This page lists categories for keyboard shortcuts. Clicking on any category should take one to the page with the shortcuts for this category. One can access this page by clicking on "View and customize shortcuts" on the [Keyboard page](https://github.com/pop-os/cosmic-settings/issues/9). 

![keyboard-shortcuts](https://github.com/pop-os/cosmic-settings/assets/57502897/0a17a798-29b2-4147-aab1-edf7d8ae8d0b)

Clicking on any category should take one to the [keyboard shortcut category page](https://github.com/pop-os/cosmic-settings/issues/33).

[Mockups in Figma.](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=7017-225065)

**Comment by PerfMonk** [comment]
Personalized keyboard shortcuts doesn't work yet.  I like using tiling mode, but without keyboard shortcuts it's kind of useless.  Any idea when they will be available ???
