### ISSUE TITLE
Settings > Input Devices > Keyboard > Keyboard Shortcuts > Keyboard Shortcut Category

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#33]
This page lists shortcuts and associated keybindings inside any keyboard shortcut category. Mockup shows "Move window" category as an example. One can access this page by clicking on any keyboard shortcut category on the [Keyboard Shortcuts page](https://github.com/pop-os/cosmic-settings/issues/32). 

![keyboard-shortcut-category](https://github.com/pop-os/cosmic-settings/assets/57502897/e13bfe48-c2a0-4d1a-87ef-302144b82791)

Clicking on a shortcut should open ContextDrawer with keybindings for this shortcut action. Users should be able to remove any of the keybindings by clicking on Delete icon button. They should also be able to input the new keybinding by clicking on the Edit icon button or double clicking the shortcut to activate the input. Additionally, there is an option to "Add keybinding" that should allow users to enter the new keybinding by pressing the key combination on their keyboard. 
![move-window-down-add-keybinding](https://github.com/pop-os/cosmic-settings/assets/57502897/324f256e-4d54-4d7e-8ec2-75401ca1169d)

If the shortcut is a duplicate of the existing shortcut, show the following dialog after someone releases the keys of the keybinding when entering the shortcut.
![Dialog-ShortcutDuplicate](https://github.com/pop-os/cosmic-settings/assets/57502897/ce046e71-262e-465a-a6a6-f38b221b62e5)

## Custom shortcuts
Custom shortcuts is a category of shortcuts that is empty be default. Below is the view when it is empty. Compared to other categories there is a button to “Add shortcut”.
![keyboard-shortcut-category-custom](https://github.com/pop-os/cosmic-settings/assets/57502897/18778629-aa24-4a58-83f6-14e8dc60ccb0)

Clicking on "Add shortcut" opens ContextDrawer where a user can enter shortcut name, command for the shortcut and keybindings.
![ContextDrawer-add-custom-shortcut](https://github.com/pop-os/cosmic-settings/assets/57502897/c193b654-9aa5-488e-9aef-f348abe78f9b)

[Mockups and more details in Figma.](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=7017-225538)

**Comment by gbonnema** [comment]
I can indeed enter a new shortcut, but it is impossible to change the name or the command afterwards. I can only delete and enter again. In 22.04 I could change either name or command. The other issue is, that the replace button, when you find a shortcut is already used, does nothing. And when you cancel because the replace doesn't work, the shortcut is gone and you have to enter it again. I could not find other people with this issue, so hopefully it is something solvable or it is a bug. OH, and I upgraded from 22.04 to 24.04 today.
