### ISSUE TITLE
Settings > Input Devices > Mouse

### ISSUE THREAD

**Issue by cozy-isaac** [pop-os/cosmic-settings#34]
![The mouse settings panel in COSMIC's Settings application](https://github.com/pop-os/cosmic-settings/assets/106764128/1c7ef776-faed-4f71-a7c8-2f02f1d6b62a)

The mouse settings panel is where users can customize mouse behaviors in a variety of ways. These settings will exist under "Input Devices" in COSMIC's Settings application.

Notes for various values:
- Primary button: Segmented control. Only available when there are multiple buttons on the mouse.
- Mouse speed: Slider with value. Values are on a scale from 1-100, where 1 and 100 are the minimum and maximum speeds we support, respectively, mapped to a percentage. A marker exists at the default speed.
- Enable mouse acceleration: Note that we've added a caption to this list item to explain acceleration. 
- Double-click speed: A slider with a value labeled in milliseconds. A marker exists at the default double-click speed.

For the mouse settings, "Scrolling" options are split off into a different section. "Scrolling speed" is using a similar relative scale as "mouse speed."

[Mockups in Figma](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?type=design&node-id=6960-179059&t=1SfV6uw2rKXoDaw4-4)

**Comment by aarongerber** [comment]
Any plans to support mice with more than three buttons?  It would be great to be able to switch Workspaces with a side button. 

I confess it's been too long to provide the details you need, but as I recall, in the distant past, I was able to see every button available for my Corsair Gaming Mouse in the terminal for X11 and map the buttons to keyboard shortcuts, but Wayland didn't have support for that so on my journey to PopOS through other distros I stopped using the feature.
