### ISSUE TITLE
Appearance Settings UI to automatically change the accent to match the wallpaper

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#343]
Only show the option if "Same wallpaper on all displays" is active.

**Comment by WatchMkr** [comment]
Let's hold on this design a bit. There's a perhaps better full-theme angle to consider long-term.

**Comment by PoisonFrog** [comment]
I would love to see an option to automatically change panel color to match the wallpaper so it blends with the desktop exactly like macOS does. I think macOS does it beautifully and it would be amazing if COSMIC could replicate that feature.
