### ISSUE TITLE
Settings > Input Devices > Touchpad

### ISSUE THREAD

**Issue by cozy-isaac** [pop-os/cosmic-settings#35]
![Touchpad settings in COSMIC's Settings application](https://github.com/pop-os/cosmic-settings/assets/106764128/83bf9b49-164e-46c9-9adb-8e7f93f0f26c)

The touchpad settings panel is where users can customize touchpad behaviors in a variety of ways. These settings will exist under "Input Devices" in COSMIC's Settings application.

Options on this page are organized by the type of interactivity with the touchpad, under the labels "Tapping and Pinching," "Scrolling", and "Swiping."

Notes for various values:
- Primary button: Segmented control. Available when there are multiple buttons on the touchpad.
- Touchpad speed: Slider with value. Values are on a scale from 1-100, where 1 and 100 are the minimum and maximum speeds we support, respectively. A marker exists at the default speed.
- Enable touchpad acceleration: Note that we've added a caption to this list item to explain acceleration. 
- Double-click speed: A slider with a value labeled in milliseconds. A marker exists at the default double-click speed.

Under "Scrolling," scrolling speed will use a slider with a value on a scale from 0 to 100 similar to touchpad speed, where the values represent a linear scale from our supported minimum and maximum speeds. 

In earlier releases, the "Swiping" area will document various three-finger and four-finger swipe actions. 

[Mockups in Figma](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?type=design&node-id=6960-194941&t=1SfV6uw2rKXoDaw4-4)

**Comment by olksndrdevhub** [comment]
Obviously not in the first Alpha, but is it possible that eventually, we can set specific actions for gestures?
As an example, for media control: 
 - three-finger swipe left/right: move to the prev/next song;
 - three-finger tap: play/pause current media.

**Comment by gabriele2000** [comment]
Will you add the option to enable/disable the touchpad too?

**Comment by jacobgkau** [comment]
This design appears to be missing the option to switch between multitouch and zoned-button modes. We're going to need that (we ship most systems in multitouch by default, but some have been shipped with zoned-button based on their touchpad design, so it's a setting we use and not something we can simply eliminate).

For reference, in the GNOME desktop-widget, this is the bullet points for `Right-Click with Two Finger Click` and `Right-Click with Click in Bottom Right Corner` (care should be taken, the copy for this section was a little complicated).

![Screenshot from 2024-02-21 14-02-38](https://github.com/pop-os/cosmic-settings/assets/7199422/17421131-abec-44f7-b71e-27be0d3b5a46)

![Screenshot from 2024-02-21 14-02-41](https://github.com/pop-os/cosmic-settings/assets/7199422/42c8c629-b254-4bd6-8ead-543a45177741)

It may be possible to simplify it a little bit now that we have our own compositor, but still may not be if it's a libinput limitation. CC @maria-komarova

**Comment by jacobgkau** [comment]
Oh, never mind, it looks like "click behavior" was added in https://github.com/pop-os/cosmic-settings/issues/68. Maybe this older issue should be closed?
