### ISSUE TITLE
[Power & Battery] Power profiles should only show when PPD or system76-power are present

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#350]
![screenshot-2024-05-31-16-09-01](https://github.com/pop-os/cosmic-settings/assets/3430283/0015e830-e08e-4b9b-95b9-f09ea4630b97)

**Comment by burakturkerdev** [comment]
It's already working like that. Except, it shows a message about there is no installed backend.

Sorry for fonts and icons, i don't have all cosmic dependencies on my laptop.

![20240601_16h53m55s_grim](https://github.com/pop-os/cosmic-settings/assets/166562458/f371f4cf-eb1d-4244-a39e-02c726ad6182)
