### ISSUE TITLE
Changing fractional scaling on external monitors causes separated or overlapping displays

### ISSUE THREAD

**Issue by brandonbaez7** [pop-os/cosmic-settings#378]
If you have 2+ monitors connected and change the scale in COSMIC settings, you will end up with overlapping displays. Realigning the displays will either create areas of the display where you can't move the mouse cursor over to the external display, or a situation where you move the cursor to the external monitor and it ends up in a different position to where you would expect. 

It seems as if the scaling causes the "screen size" of the other display to shrink to an actual 75% scale and behaves as such.  A photo below shows the effects of changing monitor 0 (the external display) to 75% scale whereas the other monitor (a laptop monitor) remains at 100%.

![screenshot-2024-06-13-21-23-58](https://github.com/pop-os/cosmic-settings/assets/160044194/e2ea2903-9684-430b-a92f-5994b6bff506)

Changing display 0 back to 100% results in an unusable display 0 as the displays become separated. This is fixed by realigning the displays again in settings. A photo of this is below:

![screenshot-2024-06-13-17-12-23](https://github.com/pop-os/cosmic-settings/assets/160044194/f2719b7e-d1fc-42d0-a21b-554e50ff1976)

**Comment by Elias-Graf** [comment]
Was that released? Still seems to be happening in `cosmic-settings 0.1.0`.
![image](https://github.com/user-attachments/assets/c0d2d85f-23f3-42d5-96fa-a9659d2543ae)
