### ISSUE TITLE
Wrong icon color in add applet section

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-settings#386]
Notice the black color for the clipboard manager applet. In the panel, the same icon get the right color (white for dark mode, and black for light mode).

![screenshot-2024-06-26-19-15-54](https://github.com/pop-os/cosmic-settings/assets/78230769/3c68136a-2cfc-4ead-9997-48291e2435d5)

**Comment by wash2** [comment]
Is the icon marked as symbolic?

**Comment by wash2** [comment]
If it is marked as symbolic, it will be colored correctly, otherwise it is assumed to not need recoloring.

**Comment by wiiznokes** [comment]
I see thanks
