### ISSUE TITLE
Cannot bind modifier + Space

### ISSUE THREAD

**Issue by curiousercreative** [pop-os/cosmic-settings#393]
Prior to recent feature for keyboard shortcut binding in settings GUI, modifier + Space was a valid keybinding in /etc/cosmic-comp.config.ron. Now, the settings GUI will not validate or accept any modifier + Space keybinding. 

See chat [message](https://chat.pop-os.org/pop-os/pl/8shpdo868jnzzb75aof454dyrc) and [thread](https://chat.pop-os.org/pop-os/channels/cosmic-epoch/go7tgcr3jtrufezjf8d1tw13dy) for more discussion.

**Comment by mmstick** [comment]
Duplicate of #390 which is already fixed

**Comment by mmstick** [comment]
Nevermind. I do see that the name is case-sensitive

**Comment by Beethoven-n** [comment]
i tried doing Super+Space as a hotkey and it didn't work, am i doing it wrong?
