### ISSUE TITLE
(Settings-> Mouse & Touchpad) No Touchpad settings to control number of lines to scroll.

### ISSUE THREAD

**Issue by centaurusgod** [pop-os/cosmic-settings#40]
Please include a graphical interface to control the number of lines to scroll on the touchpad settings. While the current touchpad settings provide a satisfactory experience, having a graphical interface would greatly enhance the user-friendliness and convenience of adjusting the scrolling behavior.

With a graphical interface, users would be able to easily fine-tune the scrolling speed and responsiveness to their personal preferences. This feature would be particularly valuable for individuals who rely heavily on touchpad navigation, such as designers, content creators, and those with limited mobility who benefit from touchpad accessibility options.

**Comment by WatchMkr** [comment]
Scroll speed fr mice and touchpads has been implemented in Settings > Input.
