### ISSUE TITLE
Global Shortcuts for Play/Pause, Previous & Next track

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-settings#408]
It will probably be added later on but what would be the command to use in the new Cosmic DE, so I can setup a shortcut manually right now?

**Comment by Drakulix** [comment]
Depends on your music player. If it supports MPRIS like many linux players do, you could use something like `playerctl`.

**Comment by senntore** [comment]
Thanks! It works. Though while setting the shortcut, I found that I had to use lower case just for 'space' rather than 'Alt+Shift+Space', otherwise the shortcut is not saved.

**Comment by WatchMkr** [comment]
We'll improve the experience for alpha 2 https://github.com/pop-os/cosmic-settings/issues/466
