### ISSUE TITLE
Panel cannot be disabled although dock can replace panel

### ISSUE THREAD

**Issue by cfuehrmann** [pop-os/cosmic-settings#430]
I use cosmic-session-git on Arch.

Please look at the screenshot below.
![panel-dock](https://github.com/user-attachments/assets/e956d4be-1972-4842-97d1-0df92b04fa23)

The top bar is the panel. The bar below that is the dock, which I configured to look like the panel. (That in itself seems funny: If the dock can do all the panel can do, plus hold an app tray, then what's the point of the panel?)

Now suppose I want to use the dock as in the screenshot, so I can have the app tray without sacrificing screen space. Then I would want to disable the panel. But I can't find a button for that.

More generally, I'd like to understand the rationale of having both a dock and a panel with such large feature overlap.

**Comment by mmstick** [comment]
The dock is just a second panel. So if you only want one panel, disable the dock and configure the panel as a dock.

**Comment by cfuehrmann** [comment]
But my settings dialog for the panel does not allow to add the app tray!

**Comment by wash2** [comment]
> But my settings dialog for the panel does not allow to add the app tray!

You can create an issue in the cosmic-settings repository for that with the relevant details. The app tray should be an option in the Add Applet drawer

**Comment by cfuehrmann** [comment]
Thanks for the info!
