### ISSUE TITLE
Settings dialog for panel does not offer app tray applet

### ISSUE THREAD

**Issue by cfuehrmann** [pop-os/cosmic-settings#431]
In contrast to the settings dialog for the dock, the settings dialog for the panel does not allow to add the app tray as an applet. That would come in handy though.

**Comment by wash2** [comment]
Could you provide more details like what version of cosmic-settings / cosmic-applets are you using, and maybe a screenshot?

**Comment by cfuehrmann** [comment]
I am awfully sorry I was wasting your time. As I was just about to make a screenshot, I found that I had previously failed to spot the app tray among the panel applets. Very sorry.

(It seems the fact that I review tons of code issues every day did not make me good at reporting them.)

**Comment by wash2** [comment]
No worries, thanks for double checking!
