### ISSUE TITLE
Settings > Bluetooth

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#437]
Settings page that allows to manage settings for Bluetooth devices. 
![Bluetooth](https://github.com/user-attachments/assets/ce3961a5-47be-4f75-8450-0ff2456ce306)

[Figma file with more details](https://www.figma.com/design/Z6Z9Ox6WNkiiM8gcAkcElS/COSMIC-Settings-First-Release---Developer-Handoff?node-id=13857-1180&t=afTfg818R0XgQy4L-1).

**Comment by acolombier** [comment]
I have started looking into that feature. I assume this will part of another cosmic service, but do we already have an issue in the according repo/design for Bluetooth interaction? (e.g PIN pairing validation, file incoming, pairing request, ...)

**Comment by acolombier** [comment]
Couple of question regarding the expected behaviour and design:
- How is the device list ordered? Status (Connected first, then disconnected) and alphabetical order?
- Do we want to display the nameless device using the MAC address?
- I'm confused with the following view
  ![image](https://github.com/user-attachments/assets/948b4458-0850-4033-ab74-4903f3f90545)
  I understand it would be shown as main screen if there is multiple adapters. If so
  - What do we do with status caption? Shall we list the alias (e.g `This system is visible as “pop-os” and “foobar” while the Bluetooth settings is open.`)
  - Once clicking on an adapter, do we show the default main scren with some kind of back button/header copy change (e.g `Bluetooth > Bluetooth adapter ID1`)
 

Just to give a glimpse of where I am at, here the current UI.

![image](https://github.com/user-attachments/assets/a0b39980-fe6d-4119-8c1a-1066468456b7)


I found a `context_menu` component on `libcosmic` but it only seem to wrap component to react right click. Is there any existing context menu allow programmatic spawn management or does this remains to be developed?

**Comment by mmstick** [comment]
> How is the device list ordered?

Similar to WiFi, by signal strength

> existing context menu allow programmatic spawn management or does this remains to be developed?

Are you looking for the popover widget? https://github.com/pop-os/cosmic-settings/blob/networking/cosmic-settings/src/pages/networking/wired.rs#L446

**Comment by maria-komarova** [comment]
I only saw the questions yesterday. About the situation with multiple adapters:
> What do we do with status caption? Shall we list the alias (e.g This system is visible as “pop-os” and “foobar” while the Bluetooth settings is open.)

I'm not sure on the details. If one has multiple adapters each of them will impose a different name on the system in general?

>  Once clicking on an adapter, do we show the default main scren with some kind of back button/header copy change (e.g Bluetooth > Bluetooth adapter ID1)

I added the view to the mockups. 
![Bluetooth - Adapter 1](https://github.com/user-attachments/assets/2f51be36-27f8-4bff-a695-a23ee0275515)

> I assume this will part of another cosmic service, but do we already have an issue in the according repo/design for Bluetooth interaction? (e.g PIN pairing validation, file incoming, pairing request, ...)

- PIN validation - the mockup has been added to Figma. We can show a dialog asking to confirm PIN validation if it is required after one clicks Connect and the system tries to establish connection. 
![Bluetooth-pairing](https://github.com/user-attachments/assets/48e1295f-1e56-41b9-913c-339f45c4875c)
- Pairing request - doesn't look like we need it. The system is visible when Bluetooth settings or the Bluetooth applet are open. When they are closed, the system is not visible so we won't have random requests coming in. 
- Sending files over Bluetooth is beyond the first release scope.

**Comment by acolombier** [comment]
> If one has multiple adapters each of them will impose a different name on the system in general?

I *believe* that by default, adapters will be aliased by Bluez with the system hostname, so they will have the same name. However, they may be configured later to have individual names, either by CLI (e.g `bluetoothctl`) or with third party apps, so still a use-case to expect. 

I have already implemented the suggested approach, with the `"name1" and "name2"` in case they differ.

> About the situation with multiple adapters... I added the view to the mockups.

Thanks for that. It looks I had implemented a similar design, just need to configure the `Bluetooth` title to behave as a back button (I assume this is what is intended?) 

> > I assume this will part of another cosmic service, but do we already have an issue in the according repo/design for Bluetooth interaction? (e.g PIN pairing validation, file incoming, pairing request, ...)

> * PIN validation - the mockup has been added to Figma. We can show a dialog asking to confirm PIN validation if it is required after one clicks Connect and the system tries to establish connection.

Looks good! That's something that will (likely) have to be implemented into `cosmic-osd` as well as we need to register an agent  which runs constantly, not just during the setting adjustment. This will allow reauth (PIN validation after a disconnection) as will as file receiving on the future release.
We could also have a temporary agent ran by cosmic-settings allowing a better integration with the setting UI. I will try to give that a go.

**Comment by maria-komarova** [comment]
> Thanks for that. It looks I had implemented a similar design, just need to configure the Bluetooth title to behave as a back button (I assume this is what is intended?)

Yes, it is a back button. You can check how Wallpaper and Appearance page are done for this.

**Comment by WatchMkr** [comment]
Leaving open and in the alpha 3 milestone for the bluetooth pin feature.

**Comment by mmstick** [comment]
PIN confirmation added by https://github.com/pop-os/cosmic-settings/commit/894cf9fc3f0b97c2b7ef6781ab8470ab77e03ced
