### ISSUE TITLE
Settings > System & Accounts

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#442]
System & Accounts page provides access to sub-category pages.

![System   Accounts](https://github.com/user-attachments/assets/e40a59eb-84d3-47c9-9040-ee4721bcb909)

[Figma file](https://www.figma.com/design/yFxlLCtVYLHMuHBNSXLf7O/Icon-theme?node-id=2616-89&t=yPr89l13DSf2haiq-4).

**Comment by WatchMkr** [comment]
Startup Applications likely go here as well.
