### ISSUE TITLE
Page titles disappear when window is shrunk vertically

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-settings#449]
The titles of pages (e.g. Desktop) disappear when the window is shrunk vertically, instead of a scrollbar appearing and the titles remaining. The scrollbar currently appears after titles have disappeared.
Causes the "Desktop" title to not be present on inital app launch until the window is enlarged vertically with the extra entries from #448, with the default window size.

**Comment by wash2** [comment]
Ok, I've got a fix for this. I'll push the fix before merging #448
