### ISSUE TITLE
Latest version of System & Accounts doesn't show Users and Firmware pages

### ISSUE THREAD

**Issue by DW8Reaper** [pop-os/cosmic-settings#457]
In the Settings app on the System & Accounts page the Users sub page and Firmware sub page no longer load they just show an empty group box:
![screenshot-2024-08-03-22-23-54](https://github.com/user-attachments/assets/8e255fc2-75f2-4664-b081-4e21af9b7d95)
![screenshot-2024-08-03-22-24-07](https://github.com/user-attachments/assets/6a7231c0-637b-4783-b337-191529d1bab8)

The About page still works just fine
![screenshot-2024-08-03-22-24-03](https://github.com/user-attachments/assets/ef2f0406-4d1b-4b96-9b6d-cf4cd93b8a00)

My system has all updates installed (PopOs) as of Augest 3 let me know if you need any more details

**Comment by git-f0x** [comment]
Those pages aren't yet implemented.

**Comment by DW8Reaper** [comment]
Whoops ok my bad then should I close this issue as Done or Wont Fix? I don't see a way to delete it.

**Comment by git-f0x** [comment]
Probably done, since it will be fixed for alpha 2.
