### ISSUE TITLE
High CPU usage on Date & Time page

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-settings#461]
When the Date & Time page is open, htop reports 100% CPU usage by cosmic-settings, and resizing and moving the window becomes choppy.

**Comment by wash2** [comment]
Is this issue occurring after interacting with the page in a specific way? I can't seem to recreate it.

**Comment by git-f0x** [comment]
Just opening the page results in high CPU usage and choppiness.

**Comment by git-f0x** [comment]
This has been fixed by the latest commit.
