### ISSUE TITLE
Context menus do not open in search results

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#468]
For example, can't change the compose key from search results because the ContextMenu doesn't open.

![image](https://github.com/user-attachments/assets/1699dcb0-963a-4120-b942-972ff01bba14)

**Comment by darthmall** [comment]
I'm seeing this issue independently of searching in the settings. Even if I navigate to the keyboard page from the sidebar, I can't change my compose key.

Is there a way to activate the compose key outside of settings in the meantime?

**Comment by mmstick** [comment]
Fixed in 0dbc1e9becb7248e50edd5d223f475e7ef74fd0c
