### ISSUE TITLE
[FEATURE REQUEST] Allow using Enter as well as Return in keyboard shortcuts

### ISSUE THREAD

**Issue by bluescorpion35** [pop-os/cosmic-settings#469]
Currently, only return is accepted, not enter

**Comment by iamevie** [comment]
Same with Space :)

**Comment by mmstick** [comment]
xkb keysysm names are case-sensitive. Space is `space`

**Comment by iamevie** [comment]
@mmstick thank you. It works fine now, just a bid confusing as it auto capitalizes the space afterward in the preview.

**Comment by Drakulix** [comment]
This will probably not be fixed as the correct solution here is to just capture the shortcut, which we will rather work on. The current behaviour is merely a stop-gap solution for the alpha release.
