### ISSUE TITLE
[Feature Request] Add a "Disable" option for "Desktop > Window Management > Super Key"

### ISSUE THREAD

**Issue by nurho** [pop-os/cosmic-settings#472]
Based on searching questions on this issue for Gnome, many users (including myself) seem prefer the super key to behave purely as a modifier and not have an action on its own.

On Gnome there was a gsettings option to disable the overlay key but not a GUI option. I think the "Desktop > Window Management > Super key" setting would perfectly suit having a "Disable" option in the existing drop-down so that in addition to being able to change the super key behaviour, it can be disabled entirely.

**Comment by Drakulix** [comment]
For what it's worth you can already do that in a config file.

Under `~/.config/cosmic/com.system76.CosmicSettings.Shortcuts/v1/custom` (which should exist if you modified any shortcuts), just add to the list of custom shortcuts:

```
    (
        modifiers: [
            Super,
        ],
    ): Disable,
```

I agree we should have a GUI option for this behaviour.

**Comment by nurho** [comment]
Thanks for the tip @Drakulix! Good to know that there is a way but yes, a GUI option would still fit nicely here I think.
