### ISSUE TITLE
Pannel and Dock "automatically hide" option doesn't apply untill signing off

### ISSUE THREAD

**Issue by FMorschel** [pop-os/cosmic-settings#473]
Not sure this is an issue to be under "settings" but the Pannel and Dock "automatically hide" option doesn't apply until signing off.

**Comment by WatchMkr** [comment]
I'm unable to reproduce this. If there are no windows on the desktop, the panel should wide but not until a window is launched.

If that's not it, please describe your panel and dock settings.

**Comment by FMorschel** [comment]
Hey! I've tested it again today! Not sure if I had a window there or something but today it did hide when I clicked the option. So I'll close this. Thanks!
