### ISSUE TITLE
Display info wrong when using an LG C3  TV 

### ISSUE THREAD

**Issue by Matt-1-2-3** [pop-os/cosmic-settings#483]
My HDMI monitor is an LG C3 43' tv. KDE is able to recognize it as an LG TV as well as the proper dimensions. Cosmic DE sees it as an external monitor 72"

**Comment by erenoglu** [comment]
Also confirmed for LG C2 42" TV being used as a Monitor

**Comment by l-const** [comment]
I have a similar issue with one 29 and one 34 inch but both cosmic & gnome are showing both as 34. This is from gnome software center: 
![Screenshot from 2024-10-20 15-15-40](https://github.com/user-attachments/assets/cb8d6487-e6db-4af4-bbfc-41b9da86392f)

**Comment by Drakulix** [comment]
This is a problem of the monitor, see https://github.com/pop-os/cosmic-randr/issues/29

**Comment by mmstick** [comment]
cosmic-settings directly displays the information provided by cosmic-randr, which gets it directly from the compositor, which gets that from the display's EDID info. So the only fix would be either to fix the EDID info at the source.
