### ISSUE TITLE
Over Amplification

### ISSUE THREAD

**Issue by NeoT42** [pop-os/cosmic-settings#484]
Hello,  I am unable to find the over amplification button under settings or anywhere else.  This was the setting that allowed me to increase the volume of 100%.  This is important for people like me that have hearing impairment.  Thank you.  Love COSMIC and what you are doing.  Keep up the fabulous work.

Tony

**Comment by WatchMkr** [comment]
@pop-os/ux we have a design consideration here. In sound settings users can increase volume above 100%. This isn't possible in the sound applet or via hotkeys or visible in the volume OSD.

There are at least two options:

1. Always allow volume to 150% and show a tick where they're going over 100%
2. Add a toggle in settings that changes the available volume from 1-100% to 1-150%

Personally, I think 1 makes more sense.

**Comment by NeoT42** [comment]
Hello, I agree with #1. It seems the easiest for someone to understand quickly. Thank you! Tony On Aug 20, 2024, at 4:32 PM, Carl Richell ***@***.***> wrote: @pop-os/ux we have a design consideration here. In sound settings users can increase volume above 100%. This isn't possible in the sound applet or via hotkeys or visible in the volume OSD. There are at least two options: Always allow volume to 150% and show a tick where they're going over 100% Add a toggle in settings that changes the available volume from 1-100% to 1-150% Personally, I think 1 makes more sense. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by maria-komarova** [comment]
I'm fine with #1 and matching the sound applet and OSD to the design in Settings, just wondering if there should be a stronger indication that one crosses into the over-amplification.

**Comment by NeoT42** [comment]
I might suggest that once you go over 100% then the slider becomes red from green denoting that you are over 100% and to be careful with your hearing. On Aug 21, 2024, at 4:08 PM, maria-komarova ***@***.***> wrote: I'm fine with #1 and matching the sound applet and OSD to the design in Settings, just wondering if there should be a stronger indication that one crosses into the over-amplification. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by git-f0x** [comment]
Personally, No. 2 makes potentially more sense from a UX and consistency perspective.
With No. 1, either the bars in the applet and OSD will in most cases be partially filled (100/150), or the bar goes to 100% (full length), while the numbers keep incrementing up to 150%, which would create inconsistency with Settings.
In either case, having over-amplification always enabled can lead to unexpected behavior to users (e.g. using hotkeys or grabbing the applet slider to quickly increase the volume to max, which is usually expected to be 100%).
A toggle similar to GNOME and KDE (with possibly a disclaimer in the description) would enable cleanly separating the 2 states, and have all volume bars/sliders go to the same value. From a UI perspective, the OSD in GNOME has the bar section past 100% turn red, but not sure how that can be adapted to accent colors.
Though I might be misunderstanding No. 1.

**Comment by WatchMkr** [comment]
OSD issue to match Settings and Applet tracked here: https://github.com/pop-os/cosmic-osd/issues/69
