### ISSUE TITLE
Missing visual indication of custom accent colour

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-settings#486]
Once a custom accent colour has been set, there is no longer visual of which box you're supposed to press to actually set a custom accent colour, you just have to remember that you need to press the final box in the list

Before setting:
![image](https://github.com/user-attachments/assets/827f5f6e-47d3-43b5-88af-4ea74175337e)

After setting:
![image](https://github.com/user-attachments/assets/c482eb3c-3cb0-463d-b847-0ed67c227efa)

**Comment by git-f0x** [comment]
It's present in the [designs](https://www.figma.com/design/Z6Z9Ox6WNkiiM8gcAkcElS/COSMIC-Settings-First-Release---Developer-Handoff?node-id=9116-107427&t=uyYmWPsBTVatihkJ-4), but isn't implemented yet.

**Comment by WatchMkr** [comment]
tracking on https://github.com/pop-os/cosmic-settings/issues/103
