### ISSUE TITLE
Excessive empty space in Displays configuration

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-settings#487]
I understand expanding the container on layouts that have more monitors but unless a user has a 6+ monitor layout there's far too much wasted space by default, alongside having a horizontal scroll bar adding even more space.

![image](https://github.com/user-attachments/assets/97585c76-007b-4073-aeae-a0bfd27f09ce)

**Comment by WatchMkr** [comment]
The scrollbar may not be necessary any longer. There was a point when a display could become disconnected from another and scrolling was necessary to find it. @mmstick what do you think? Can we remove the scrollbar?

I think vertical monitors are part of what's making the view so much larger. For instance, the potential to put display #2 above display #1. Nonetheless there is some extra padding on top and bottom that could be removed.

@mmstick @maria-komarova what looks like extra padding can be seen when dragging a window above another and before letting go. The space between the "Drag displays..." and the top, and the space between the window and the notice seem that they could be halved.

![image](https://github.com/user-attachments/assets/d6bc6a17-4b6e-4e81-ac04-6aa28b0c861e)
