### ISSUE TITLE
cosmic-settings fails to open if there are issues with wdisplays

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-settings#508]
not sure how to reproduce 100%.

serw13 - RTX4070 - 2 external displays connected.
If i adjust the placement of a display in cosmic-settings and then close cosmic-settings, i can no longer open cosmic-settings until i run the following command to kill it:
```
killall cosmic-settings
```

this behavior happens in conjunction with `wdisplays`. after applying display settings in cosmic-settings, wdisplays will fail to work at all for anything with the following error:
```
The display server was not able to process your changes.
```

![image](https://github.com/user-attachments/assets/a4bdf319-5b08-49f7-a9c5-3994e18ea8dc)

modifying/deleting `~/.local/state/cosmic-com/outputs.ron` does not help with this issue.

---
```
cosmic-comp: 0.1~1723813191~22.04~a3c8111
cosmic-settings: 0.1.0~1723893909~22.04~83a4296
```

**Comment by WatchMkr** [comment]
@garrettjwilke is this still happening?

**Comment by garrettjwilke** [comment]
this seems to be fixed. I can orient the displays in several ways without issues, and Cosmic-Settings opens every time and allows me to change the display configuration.

:)
