### ISSUE TITLE
resizing window, some ui elements stop scaling down

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-settings#514]
```
cosmic-settings: 0.1.0~1723893909~22.04~83a4296
```

in the "Appearance" section, there is the option to choose the "Style" (rounded, square, etc). When resizing the cosmic-settings window, the contents for the "Style" elements scale up/down according to the size of the window. if you resize smaller, eventually these elements in the "Style" section will no longer scale down, and will resize back to original size scaling.

video attached:

https://github.com/user-attachments/assets/388ccdf3-a2b8-43fe-8e94-4cc5e23e6837

**Comment by WatchMkr** [comment]
This is better than scaling down further where the image would be too small to easily identify the corners that are changing.
