### ISSUE TITLE
resizing window - sound volume sliders not consistent with other sliders

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-settings#515]
```
cosmic-settings: 0.1.0~1723893909~22.04~83a4296
```

when resizing cosmic-settings with a slider on screen, in most cases the slider will move beneath the settings indicator-text in order to have room to adjust/slide. See video below for expected behavior:

https://github.com/user-attachments/assets/f3fdda83-1faa-422c-a7fc-1fcedac92d4b

when resizing cosmic-settings in the "Sound" settings, the volume sliders do not exhibit the same behavior. instead, the sliders get smaller to the point that they are unusable. expected behavior is that the volume sliders will move beneath the indicator-text to allow room like other sliders in settings. see video below of unexpected volume slider behavior:

https://github.com/user-attachments/assets/cb7329f8-ce96-4176-9ce2-69ca9d21a73f

**Comment by l-const** [comment]
Hey @garrettjwilke, I did reproduce it and manage to fix it in (a46587fb)https://github.com/pop-os/cosmic-settings/commit/a46587fb , just letting you know.
