### ISSUE TITLE
[FEATURE REQUEST] be able to add a keyboard shortcut to change the keyboard layout

### ISSUE THREAD

**Issue by nimafanniasl** [pop-os/cosmic-settings#530]
Hey!
I have two keyboard layouts and switch between them a lot, and in COSMIC, I couldn't find any option to set a keyboard shortcut for changing the layout.
It's very crucial for me to be able to switch between keyboard layouts and it's been the only roadblock for me to switch to COSMIC :)

**Comment by git-f0x** [comment]
It's not yet implemented, but it's planned.

**Comment by nimafanniasl** [comment]
Thanks a lot, it's really important for many people so hopefully, we'll see it on the COSMIC desktop soon :)
Thanks again.

**Comment by leviport** [comment]
We're tracking this here: https://github.com/pop-os/cosmic-epoch/issues/607

I'm locking this thread to direct conversation to that issue

**Comment by WatchMkr** [comment]
Closing dups for easier triage management.
