### ISSUE TITLE
Using right super as alternative character key does not work

### ISSUE THREAD

**Issue by nr23730** [pop-os/cosmic-settings#546]
Hi, i'm using Fedora Linux on a MacBook with a US-int layout. As it's right Alt-Key is in a very uncomfortable position for me, I always remap the right Super/Win/Command key to Alt as well. Fortunately cosmic has such an option!
When I tried this, typing worked great, but also the left Super/Win/Command key had the same behavior.

The issue is probably that https://github.com/pop-os/cosmic-settings/blob/b8abfc010007badffcd5b3c60861d5e12fa01df9/cosmic-settings/src/pages/input/keyboard/mod.rs#L35

says `lv3:win_switch` instead of `lv3:rwin_switch`

**Comment by Sibgatulin** [comment]
I wonder, shouldn't the same apply to right alt too?
I am using Fedora Linux too, however on a Framework laptop, and setting Alternate characters key to Right Alt has no apparent effect.
