### ISSUE TITLE
Was the Sharing settings (re)moved or planned?

### ISSUE THREAD

**Issue by gregpalaci** [pop-os/cosmic-settings#559]
![image](https://github.com/user-attachments/assets/89bbd3ae-f9dd-4935-bae4-3f4a04f21af9)

the VNC / RDP / SSH panel was handy I didn't see it, am I blind, was it removed on purpose or it's still in the works, or it moved somewhere else?

Thanks for all the hard work on everything!

**Comment by mmstick** [comment]
This isn't GNOME Settings. Such things haven't been informed yet.

**Comment by gregpalaci** [comment]
Aw no worries, thanks for the response!

**Comment by gregpalaci** [comment]
Was mostly curious if it might already be there or if it might be a security thing and I shouldn't do it myself. or a wayland vs X11 thing :P
