### ISSUE TITLE
Four finger swipe for workspaces does not respect natural scrolling setting

### ISSUE THREAD

**Issue by Nashenas88** [pop-os/cosmic-settings#562]
The four finger swipe behavior seems to enforce natural scrolling regardless of whether natural scrolling is enabled. I prefer scrolling and swiping towards the direction I want to go to see the content (the opposite of natural scrolling). For example, if I want to see the content above, I scroll up to get to it. I would expect I could do the same when switching workspaces, i.e. swipe to the right to see content on the right.

**Comment by Nashenas88** [comment]
Also, let me know if this is a feature request or not. I'll see if I can work on adding this option.

**Comment by pknepps** [comment]
Resolved by pop-os/cosmic-comp#794

**Comment by Nashenas88** [comment]
Confirmed it's working now after the fix. Thanks!
