### ISSUE TITLE
[FEATURE REQUEST] Have Cursor follows focus appear in the middle of a window

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-settings#567]
Currently cursor follows focus moves the cursor to the top left of a window, this makes it very easy to accidentally move the cursor off of the window you just moved your focus to, a lot of tiling window managers avoid this problem by moving the cursor to the middle of a window instead

https://github.com/user-attachments/assets/0051956a-8de7-44b4-b3d8-016f585c1423

**Comment by nani8ot** [comment]
Another advantage of moving the cursor to the center of the window is the shorter median distance the mouse has to be moved. I believe regularly moving the mouse a bit in each direction is better than mostly moving down to the right.

**Comment by git-f0x** [comment]
This can probably be closed, since it was implemented.
