### ISSUE TITLE
[bug]: searching through keybindings ignores custom keybinding names

### ISSUE THREAD

**Issue by GetPsyched** [pop-os/cosmic-settings#570]
I can only search through the pre-packaged keybindings, and it ignores any custom ones added even though they do have a name

**Comment by l-const** [comment]
i have a potential fix in https://github.com/pop-os/cosmic-settings/pull/574

**Comment by l-const** [comment]
I guess i did not link the PR and the issue properly, but let's close this one as well now that we merged the change, if you are ok with this @mmstick @GetPsyched .

**Comment by GetPsyched** [comment]
Thank you! I'll check this out once the package is bumped in my package manager since I don't know how to get these things building locally (I want to learn though since I also wish to contribute)

**Comment by l-const** [comment]
Hey @GetPsyched , `cargo build/run --release` after you `git clone`  the repo, also you may need to install some system libraries that you could find here: https://github.com/pop-os/cosmic-settings/blob/master/debian/control#L6-L18 .

**Comment by GetPsyched** [comment]
Awesome! Is this relatively the same for the sibling repos on here for COSMIC as well?

**Comment by l-const** [comment]
Yes, pretty much the same

**Comment by mmstick** [comment]
Every project has a `Justfile`, so you can use that to `just build/run/install`

**Comment by GetPsyched** [comment]
Thanks guys, looking forward to it!
