### ISSUE TITLE
[BUG] moving cursor outside of window while using scrollbar does not release mouse

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-settings#579]
```
cosmic-comp: 0.1~1725891687~22.04~0ffe6ae
cosmic-settings: 0.1.0~1725882156~22.04~df43c94
```

i have only seen this behavior in `cosmic-settings`. if you grab the scrollbar and begin dragging to scroll through the contents and move the mouse beyond the settings window and then release the mouse button, the mouse will not release the scrollbar. thus, when you move your mouse cursor back into the settings window, the scrollbar will not be released and will keep scrolling as if you had the mouse button held down the entire time.

https://github.com/user-attachments/assets/a3c22670-944d-48ae-b6fb-f1b490473d9e

**Comment by WatchMkr** [comment]
This appears to have been fixed with the iced update.
