### ISSUE TITLE
Fails to build due to non-existant branch/commit of cosmic-bg/cosmic-panel

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-settings#59]
Removing the `branch = "settings_jammy"` lines and running `cargo update` shows some changes needed to work with latest cosmic-bg.

CC @mmstick

**Comment by mmstick** [comment]
I don't see any lines mentioning this branch.

**Comment by ids1024** [comment]
Nevermind. Looks like I forgot I had multiple branches checked out in different locations with git worktrees, which can make things a bit confusing.
