### ISSUE TITLE
Suggestions for Improvements to the Cosmic Epoch Desktop Environment

### ISSUE THREAD

**Issue by rishikbose25** [pop-os/cosmic-settings#593]
Dear Pop_OS!,

I hope this message finds you well. My name is Rishi K. Bose, and I am a big fan of the Cosmic Epoch desktop environment. As a dedicated user, I would like to offer some suggestions that I believe could enhance the overall user experience. 

1. Reintroduce the Old Tiling Features: Features like setting exceptions (e.g., Picture-in-Picture mode in Firefox) were highly beneficial and would greatly enhance productivity.

2. Restore the Classic Pop!_OS Theme: The original theme was iconic and unique to the Pop!_OS distribution. Bringing it back would reinforce the distinctive identity of the system.

3. Incorporate Additional Gestures: Adding more touchpad and touchscreen gestures would improve navigation and usability.

4. Provide Window Management Options: Allow users to specify which window should remain on top, similar to the Picture-in-Picture option in Firefox.

5. Reinstate Night Light and Online Accounts Features: These functionalities are essential for many users and would significantly contribute to a more comprehensive desktop experience.

I look forward to the continued evolution of this desktop environment and appreciate your attention to user feedback.

Thank you for your time.

Warm regards,  
Rishi K. Bose

**Comment by mmstick** [comment]
You should make one issue per request

**Comment by rishikbose25** [comment]
Okay.

**Comment by rishikbose25** [comment]
I agree for this, sir, but these improvements could be great and useful for day to day task.
