### ISSUE TITLE
[Desktop > Panel > Applets]: No applets show up

### ISSUE THREAD

**Issue by GetPsyched** [pop-os/cosmic-settings#599]
![2024-09-16_01-01](https://github.com/user-attachments/assets/df82c59f-1f38-409c-b296-c8b74af0328e)
Same within "Add Applet" menu

**Comment by leviport** [comment]
Do you have `cosmic-applets` installed?

**Comment by GetPsyched** [comment]
Yes
```sh
~ λ which cosmic-applet
cosmic-applet-audio          cosmic-applet-bluetooth      cosmic-applet-minimize       cosmic-applet-notifications  cosmic-applets               cosmic-applet-tiling         cosmic-applet-workspaces
cosmic-applet-battery        cosmic-applet-input-sources  cosmic-applet-network        cosmic-applet-power          cosmic-applet-status-area    cosmic-applet-time           

~ λ which cosmic-applets
/run/current-system/sw/bin/cosmic-applets
```

**Comment by wash2** [comment]
what is the output of `cat ~/.config/cosmic/com.system76.CosmicPanel.Panel/v1/plugins_center`, if the file exists?

**Comment by GetPsyched** [comment]
The folder exists, the file doesn't

**Comment by GetPsyched** [comment]
I updated my system today and it seems to have been fixed, not sure in what commit though. If anyone has this issue, they're free to re-open :D
