### ISSUE TITLE
Settings > Sound

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#6]
This design needs to be paired back for the first COSMIC release.

1. Do not include speaker testing (the "Test" button and interfaces)
2. Do not include per-application volume levels

These can arrive in COSMIC V2.

-- Carl

**Comment by maria-komarova** [comment]
Final mockups for the panel are in [this Figma file](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=609%3A25719).

**Comment by workingj** [comment]
hi, 
happy to see all this nice work done!
on thing i'd like to mention:
having the slider handle and the slider bar in the same color looks a bit flat or odd to me.
in the in gnome you have they have slightly different colors, which looks way nicer... 
see the screenshot:

![Screenshot from 2023-01-12 22-09-47](https://user-images.githubusercontent.com/19818596/212182382-1348dd08-9a32-46ae-9d8a-3978671cbeef.png)

keep up the good work!
hope this helps :>

**Comment by pr0nstache** [comment]
Hopefully adding sound ducking is in the works?  It'd be really nice to set in this interface for using communications apps.  Even a check box to list streams manually.  Setting up ducking in wireplumber policies is cumbersome.

example [https://pipewire.pages.freedesktop.org/wireplumber/configuration/policy.html#policy-lua-d-50-endpoints-config-lua](wireplumber policy for ducking sounds)

**Comment by gantryyork** [comment]
None of this is implemented yet.  Will it be implemented before the alpha-release?  It makes for some inusability.  For example, my Bluetooth headset will connect, but I can't choose it as an output/input device in settings.

**Comment by WatchMkr** [comment]
> None of this is implemented yet. Will it be implemented before the alpha-release? It makes for some inusability. For example, my Bluetooth headset will connect, but I can't choose it as an output/input device in settings.

This is planned for the second alpha. You should be able to set your Bluetooth headset as the output and input device from the volume applet in the panel.

**Comment by raddessi** [comment]
Would you all include the ability to set the volume-step percentage when using media keys? For those with a rotary knob and/or external DAC the default 5% is too much so being able to set it to 1% would be great. Thanks!

**Comment by maria-komarova** [comment]
Paired back Sound panel designs ([link to Figma](https://www.figma.com/design/Z6Z9Ox6WNkiiM8gcAkcElS/COSMIC-Settings-First-Release---Developer-Handoff?node-id=709-45887&t=eofarm6n1EzumKaA-1)):
![Sound](https://github.com/user-attachments/assets/0af42bcd-ae0b-447e-b08a-9114c38bb035)
![Sound-no-devices](https://github.com/user-attachments/assets/de4bb4c2-a969-410d-b775-7484bbe89c8a)

**Comment by WatchMkr** [comment]
Implemented. Separate issues created to add [balance](https://github.com/pop-os/cosmic-settings/issues/516) (alpha 1) and [per-app volume](https://github.com/pop-os/cosmic-settings/issues/517) (future milestone)

**Comment by MrDorianJames** [comment]
I'd like a "configure" button or something in the audio applet and audio settings that goes to a pipewire editor.

**Comment by omidmash** [comment]
> Would you all include the ability to set the volume-step percentage when using media keys? For those with a rotary knob and/or external DAC the default 5% can be too much so being able to decrease it to 1% would be great. Thanks!

`dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-step 2
` 

This worked for me.
