### ISSUE TITLE
Dark theme doesn't apply to GTK3/Qt

### ISSUE THREAD

**Issue by fulalas** [pop-os/cosmic-settings#617]
Although the system is set to dark mode by default, GTK3/Qt applications (haven't tested GTK4) don't have dark theme applied.

**Comment by mmstick** [comment]
Do you have adw-gtk3 installed?

**Comment by fulalas** [comment]
Yes. If I manually run `gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"` it works straightaway.

**Comment by Drakulix** [comment]
> `gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"`.

This changes the whole GTK-theme, which COSMIC won't do, if you don't enable the experimental GNOME-apps setting.

What should be changed by `cosmic-settings-daemon` (which is why it is important, that it is running) is the `color-scheme` (`gsettings get org.gnome.desktop.interface color-scheme`).

Any theme supporting both schemes (e.g. the standard "Adwaita") should switch on the fly.

**Comment by mmstick** [comment]
cosmic-settings-daemon sets the GTK3 theme to `adw-gtk{,-dark}` if installed and GNOME theme support is enabled. The adw-gtk3 theme inherits the libadwaita/GTK4 color scheme.

**Comment by Drakulix** [comment]
> cosmic-settings-daemon sets the GTK3 theme to `adw-gtk3{,-dark}` if installed and GNOME theme support is enabled. The adw-gtk3 theme inherits the libadwaita/GTK4 color scheme.

Yes, these remarks where just about the case, where that setting is disabled. All the code is in place to still be able to have dark/light modes apply correctly across various toolkits.

**Comment by equeim** [comment]
For Qt you need to set `QT_QPA_PLATFORMTHEME=xdgdesktopportal` environment variable, and possibly install additional package depending on a distro.

**Comment by fulalas** [comment]
OK, I see now what is wrong. The Adwaita theme can also be called 'Adwaita' / 'Adwaita-dark' (notice the 'd' in lower case). Source: https://gitlab.gnome.org/Archive/gnome-themes-extra/-/blob/master/themes/Adwaita-dark/index.theme.in?ref_type=heads#L6

I can confirm running `gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'` changes my GTK3 applications theme to dark, but `gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'` has no effect.
