### ISSUE TITLE
[Bug] Unable to Change Modes and Colors in Appearance Settings

### ISSUE THREAD

**Issue by farhatizakaria** [pop-os/cosmic-settings#619]
the Appearance settings are not functioning as expected. I am unable to change color themes (using color palettes), and the experimental settings window fails to open. 

**Steps to Reproduce:**

1. Open Cosmic Setting.
2. Navigate to Desktop> Appearance.
3. Attempt to select a different color theme.
4. Try to access the Experimental Settings window.

**Expected Result:** Users should be able to customize color themes, and successfully open the experimental settings window.

**Actual Result:**

- Changing colors has no effect (color palettes doesn't open).
- Attempting to open the experimental settings window does not respond or shows an error.

**Comment by git-f0x** [comment]
This has been fixed, but the update is only available in `popdev:master`. #615

**Comment by git-f0x** [comment]
It's already available if you've enabled the `popdev:master` repo. Otherwise it will likely get pushed to the main repos on Monday.
