### ISSUE TITLE
Interface density settings in incorrect order

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-settings#627]
Usually density settings should either be smallest to largest, or largest to smallest

Right now it's middle, smallest, largest

![screenshot-2024-09-25-04-15-01](https://github.com/user-attachments/assets/1dba06f7-ec64-4aad-a757-a0caa73e6b4b)

**Comment by BrodieRobertson** [comment]
Looking at it again, that's clearly alphabetical order, it's still not correct but I'm assuming iced/libcosmic is doing some automatic sorting

**Comment by git-f0x** [comment]
It's not automatic sorting, it's just how the order is in the designs (so I followed them).
It would be easy to change (I would also prefer a semantic order), but requires UX approval.

**Comment by BrodieRobertson** [comment]
It's a very minor issue but it just doesn't feel like a natural ordering of options
