### ISSUE TITLE
[Input Devices > Mouse > Primary Button] Switching Primary button does not work as expected

### ISSUE THREAD

**Issue by EpyonProjects** [pop-os/cosmic-settings#636]
The primary mouse click function is still the Left mouse button, despite being changed and saved as Right
![screenshot-2024-09-27-18-51-39](https://github.com/user-attachments/assets/b8a1a2db-6efe-4983-91f6-5c720eaa0a33)

Hardware:
OS: Pop!_OS 24.04 (downloaded yesterday and updated as of Sept 27, 2pm EDT)
CPU: Intel i7-12700K
GPU: MSI Nvidia RTX 3080 12G
GPU driver: 560.35.03
Ram: 32 GB
Motherboard(?): ASUS TUF Gaming Z690-PLUS WIFI

**Comment by EpyonProjects** [comment]
Hmm, it seems it just didn't save.  This is an ongoing problem I have with the lack of confirmation prompt.

**Comment by jvcByte** [comment]
having the same issue #1939
