### ISSUE TITLE
[BUG] PIN notification for pairing bluetooth keyboard does not appear

### ISSUE THREAD

**Issue by goncu** [pop-os/cosmic-settings#696]
When trying to pair ERGO K860 keyboard, first 'Connected' notification appears, but then notification for PIN code that you need to enter to complete pairing does not appear and pairing fails after some time. Issue persists in Alpha 2, both in live boot and in installation.

**Comment by leviport** [comment]
Related: https://github.com/pop-os/cosmic-settings/issues/437

**Comment by WatchMkr** [comment]
Can this issue be closed?

**Comment by leviport** [comment]
I believe so. We can reopen if I'm mistaken.

**Comment by SnoozingYeti** [comment]
I see that this has been closed but having finally installed cosmic I can confirm the GUI does not give any code for pairing nor does it automatically trust after pairing.
