### ISSUE TITLE
[Bug] Custom accent color has to be changed to be reselected

### ISSUE THREAD

**Issue by shermanhlc** [pop-os/cosmic-settings#698]
Go to Desktop > Appearance and set a custom accent color. Then  select one of the default colors. When attempting to go back to the custom color, you have to change the hex/rgb value in order for the custom color to stick, else it remains on the previously selected default color.

**Comment by wash2** [comment]
You can press enter on the text input to apply the currently selected color, but I agree, maybe there could be a button there, or it could apply on opening.

**Comment by leviport** [comment]
Somewhat related: I also noticed that the hue slider doesn't update the selected color immediately, like the saturation/brightness field above it does. To change from red to blue, for example, I have to move the hue slider, then click somewhere in the saturation/brightness field above it to make it update.

If this needs to be a separate issue, I can open one.

**Comment by wash2** [comment]
Sure, that is kinda a separate issue that could be created in libcosmic.
