### ISSUE TITLE
Settings > Displays (leverage wdisplays)

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#7]

**Comment by Drakulix** [comment]
https://github.com/luispabon/wdisplays

**Comment by maria-komarova** [comment]
Mockups for the panel are in [this file](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=693%3A63625).

**Comment by pflanzenandi** [comment]
> Night light will also be available at the top of the Displays settings. Clicking on the list item will open a night light context drawer with options to enable Night light, set the color temperature, and scheduling. Night light can also be enabled directly from the Displays panel without opening the context drawer, by clicking on the toggle within the list item.
> 

Thanks for making the current mockups public. Regarding Night Light, I have been using a small but useful [extension](https://codeberg.org/kiyui/gnome-shell-night-light-slider-extension) to manually set the colour temperature via slider inside the 'fast settings panel'. This slider allows me to adjust the colour temperature depending on the light conditions e.g. when I am on the move with the laptop. The standard method of determining the colour temperature via time schedule was never sufficient nor flexible enough for me. Maybe there is a possibility to consider such a function. 
Best regards

![Screenshot-20230203163013-652x1006](https://user-images.githubusercontent.com/60046516/216645152-3c6c0921-9273-4e51-aad2-325968775145.png)

**Comment by Munoida** [comment]
Will displays be nameable? Like naming Monitor 1 and Monitor 2 something that the viewer can be able to distinguish a them a bit more?
like Left Monitor and Right Monitor for a dual monitor setup, etc.

**Comment by hyuri** [comment]
Would be really nice to have a brightness control in Night Light, or at least an "also dim the screen" checkbox, so that we not only get a warmer screen but also a less bright one at night.

**Comment by hyuri** [comment]
Also, it would be really really nice to have an exclusion list that we can add color-sensitive apps to (like creative apps such as Gimp, Krita, Kdenlive, DaVinci Resolve, etc.), that temporarily turns Night Light off when open. F.lux has that and it's really handy.

It's remarkably easy to forget you have Nigh Light on and suddenly realize you've been doing Color Grading on a video for the whole past hour and the colors are now all wrong.

**Comment by Munoida** [comment]
>>Would be really nice to have a brightness control in Night Light, or at least an "also dim the screen" checkbox, so that we not only get a warmer screen but also a less bright one at night.
>
> Also, it would be really really nice to have an exceptions list that we can add color-sensitive apps to (like creative apps such as Gimp, Krita, Kdenlive, DaVinci Resolve, etc.), that temporarily turns Night Light off when in focus.
> 
> F.lux has that and it's really handy, the apps you have open or in focus show up in the f.lux menu and you have an option to add/remove it to/from the exceptions list. When you switch to an app in the exceptions list, night light turns off (in a nice fade), and when you switch away, it turns back on again(in a nice fade as well).
> 
> It's remarkably easy to forget you have Night Light on and suddenly realize you've been doing Color Grading on a video for the whole past hour and the colors are now all wrong.

I second both of these
