### ISSUE TITLE
[Bug] Setting Secondary Monitor To the Left Offsets Items On Rightside Monitor

### ISSUE THREAD

**Issue by Joomsy** [pop-os/cosmic-settings#719]
Starting with version 0.1.0~1729612113~24.04~537592a, having monitor "1" set to the left of monitor "0" causes things like tray item context menus to skew way off to the right. I posted this issue under the comsic-panel tracker last night, but after some tinkering today, I'm starting to think this may be a problem with the settings app. If I move this secondary monitor to either the bottom, or right of the primary, the issue doesn't seem to exist. It does, however, seem to be an issue when the monitor is also on top, which instead pushing things toward the bottom. And if it's set to be underneath the primary, this seems to mess with things like Steam notifications.

Screenshot for reference:
![screenshot-2024-10-23-05-43-36](https://github.com/user-attachments/assets/41982366-a73f-4e6d-8f9c-3c84d67dcd6a)

**Comment by Joomsy** [comment]
> The settings app doesn't create those menus

No, but it does handle monitor layout positions, and that seems to be the source of the issue. As mentioned, the position of a secondary monitor is what's affecting these menus.

**Comment by mmstick** [comment]
It configures display positions, but doesn't handle displays. That would be the compositor.

**Comment by Joomsy** [comment]
> It configures display positions, but doesn't handle displays. That would be the compositor.

Ah, I figured it would be the next one in line. :)
