### ISSUE TITLE
[Bug] No options in power menu other than Power Mode

### ISSUE THREAD

**Issue by Griffen8280** [pop-os/cosmic-settings#722]
Not sure if this is because I have this installed alongside the regular Gnome DE that ships with PoPOS however my Power&Battery section screenshot is quite bare in comparison to the one of what the settings menu is supposed to look like.  One of the options I'm sorely missing is the auto monitor off timer.  Not sure if this is due specifically to a bug or some sort of setting/package that isn't properly turning on when I load the DE.

![screenshot-2024-10-26-12-22-41](https://github.com/user-attachments/assets/948a56e5-61e0-40db-8f72-403873f8c906)

**Comment by l-const** [comment]
Hey @Griffen8280 , if you are talking about the power & savings settings then it is still in development , see here: https://github.com/pop-os/cosmic-settings/pull/704

**Comment by Griffen8280** [comment]
@l-const Ok roger, wasn't sure if this was a known issue or something that only I was experiencing.  If it helps I can post the specs of my machine and chips here.  I've been running cosmic for a bit and haven't encountered any major/minor bugs yet except this one.
