### ISSUE TITLE
[BUG][French] Typo present in the words 'Pandant' and 'Precedemment' in the Bluetooth settings page

### ISSUE THREAD

**Issue by Zakadius123** [pop-os/cosmic-settings#723]
Cosmic-settings version: 0.1.0~1729783460~24.04~3d01bda

The word 'pandant' should be 'pendant'.
'Precedemment' is missing the accents, it should be 'précédemment'.

Repro-steps:
1. Have language set to 'French'
2. Proceed to the Bluetooth settings page.
3. Observe typos.
![image](https://github.com/user-attachments/assets/97626751-e5f0-4bcf-9419-bf5a3e0e6adc)

**Comment by acolombier** [comment]
Oops that would be my fault. Do you want to submit a PR and update [the file](https://github.com/pop-os/cosmic-settings/blob/master/i18n/fr/cosmic_settings.ftl) accordingly?

**Comment by Zakadius123** [comment]
I have never done a PR. Would I just press on "Fork this repository" (pen icon) and edit from there?

**Comment by acolombier** [comment]
Yes, that should be it!
I can help with that otherwise.

**Comment by Zakadius123** [comment]
I think that's it.
