### ISSUE TITLE
Remove settings from Desktop and Panel page

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#73]
Remove some settings that aren't wired up yet:

1. Hot corners aren't designed to work with auto-hiding panels and probably won't be for release.
2. Top panel applets/options are now configured under Panels

![remove_settings](https://github.com/pop-os/cosmic-settings/assets/3430283/caf5623a-6e5e-4172-a005-8782537b359b)

**Comment by wash2** [comment]
Should be fixed by #74
