### ISSUE TITLE
[Feature request]: Crtl + q  shortcut closes window.

### ISSUE THREAD

**Issue by l-const** [pop-os/cosmic-settings#735]

**Comment by git-f0x** [comment]
Can't this be added in keyboard shortcuts settings? It seems to work for me when I add it there.

**Comment by l-const** [comment]
As a custom keyboard  shortcut? i mean essentially it should be builtin like in files/edit e.g: https://github.com/pop-os/cosmic-files/blob/master/src/key_bind.rs#L55 , it is just we do not have specific keyboard mapping / binds / action subscription for this app? Anyway, it is an easy thing to implement i just was using the app in tiling mode and it annoyed me that this was the only cosmic app it didn't work (cosmic-term closes with ctrl+d)

**Comment by git-f0x** [comment]
You can set a global keyboard shortcut for closing windows in Settings. Or do you mean something else?

**Comment by l-const** [comment]
I guess that will do, thnx!

**Comment by mmstick** [comment]
Super+q already closes windows in COSMIC

**Comment by l-const** [comment]
I guess there is not consistency between the ecosystem, but depending the application the close window and exit application (process.exit()) could be a separate thing: https://askubuntu.com/questions/46917/what-is-the-purpose-of-alt-f4/46920#46920, if some processes could continue running on the bg.
