### ISSUE TITLE
[Applets] Drag and drop is offset depending on scroll position

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-settings#756]
When the scroller is at the top, dragging applets works as expected.
When the scroller is moved downwards, and an applet is picked up, the applet drop location is displayed offset (upwards) from the cursor position by the amount scrolled.
![screenshot-2024-11-05-01-31-25](https://github.com/user-attachments/assets/350674b0-ec32-4e8f-ad9d-9b0cc5cfbf46)

**Comment by mmstick** [comment]
I noticed that it works only when the window is maximized

**Comment by git-f0x** [comment]
Fixed!
