### ISSUE TITLE
Not Possible to change display scaling when 1 screen is disabled.

### ISSUE THREAD

**Issue by marchaesen** [pop-os/cosmic-settings#767]
When 2 screens are attached to the pc, but 1 screen is disabled, the possibility to change the scaling of the screen is not  there anymore:
Settings page with 2 screens attached and both enabled:
![screenshot-2024-11-07-15-22-23](https://github.com/user-attachments/assets/8e343d72-12b6-41cc-835a-2641112145c2)

Settings page with 2 screens attache but 1 is disabled:
![screenshot-2024-11-07-15-18-24](https://github.com/user-attachments/assets/d8915afc-4414-454d-b0ae-5c79216632fa)

**Comment by WatchMkr** [comment]
I am unable to reproduce this. Is is the issue fixed for you now?
