### ISSUE TITLE
Can't define keyboard shortcut with "enter"

### ISSUE THREAD

**Issue by JudeLingan** [pop-os/cosmic-settings#787]
In order to use the enter key for a keyboard shortcut, I have to type "return" (case sensitive). I think that this hinders user-friendliness as many people refer to the "return" key as enter, and that is what is printed on it on many keyboards. I could see a lot of people not realizing this and just thinking it's flat out broken.

**Comment by WatchMkr** [comment]
Our solution to this is being tracked here: https://github.com/pop-os/cosmic-settings/issues/499

The plan is to capture modifiers like Super and Space automatically.
