### ISSUE TITLE
Using space in keyboard shortcuts is case sensitive

### ISSUE THREAD

**Issue by JudeLingan** [pop-os/cosmic-settings#788]
I tried to set Super+Space as the the keyboard shortcut for the launcher, but it wouldn't let me until I typed "Super+space" instead of "Super+Space". This is both difficult and inconsistent because "Super" is capitalized. I think that at the very least, all keys should be capitalized, but a better solution might just be to make everything case-insensitive. That way people don't run into as many issues.

**Comment by WatchMkr** [comment]
Our solution to this is being tracked here: https://github.com/pop-os/cosmic-settings/issues/499

The plan is to capture modifiers like Super and Space automatically.
