### ISSUE TITLE
Settings > Input Devices

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#8]

**Comment by maria-komarova** [comment]
![input-devices](https://github.com/pop-os/cosmic-settings/assets/57502897/64757b85-cfb0-4f4f-802e-ff429e6f305b)
[Mockup in Figma](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=6921-72822). 

[Keyboard panel](https://github.com/pop-os/cosmic-settings/issues/9).

**Comment by Drakulix** [comment]
> Will there be settings for input devices like Wacom graphic or display tablets?

Likely not in the first alpha, but eventually yes. Absolutely.
