### ISSUE TITLE
Unclear if date settings are mm/dd or dd/mm

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-settings#815]
Currently under the new date settings it shows the date as 01/01/2024 this makes it very unclear if it's supposed to be showing dd/mm/yyyy or mm/dd/yyyy this should either be set to January 2nd or any other date where the month and day are not the same number or simply just show it as the letter form, dd/mm/yyyy, etc

![screenshot-2024-12-12-09-55-26](https://github.com/user-attachments/assets/2d526639-bb2d-4a0b-b67b-58ce2634052a)

**Comment by stalkerg** [comment]
I believe it's should depend on your locale, and you will not confuse, but yes, sometime you don't know behavior for your locale. I am constantly switching between English, Japanese and Russian, this is why it's can be a good extra tip.

**Comment by Keloran** [comment]
yeah would be better if it was

22/01/2024

then you know its not inside the 12 months

**Comment by BrodieRobertson** [comment]
The main concern I have is if you're unaware what your locale uses or if for one reason or another you need to set your system to another locale

**Comment by KaiserCalm** [comment]
I agree with @Keloran while the merged pr sets the day and month to different numbers the month is still under 12. Being able to look at the date and see something like 31/01/2025 would make it immediately obvious which number is the day and which one is the month.

**Comment by tafia** [comment]
Yeah, something like August 20, 1977, date of Voyager 2 space probe launch would have been a better pick for COSMIC.
