### ISSUE TITLE
COSMIC settings sidebar ordering feels random

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-settings#818]
I'm not sure if the intention is for the items to be ordered by how frequently a user might want to see them or possibly some other logic but to me they appear to be randomly sorted. Alphabetical ordering would make much more sense

![screenshot-2024-12-12-10-53-14](https://github.com/user-attachments/assets/9a2f7cb7-54fd-46f0-a01e-3f1b8837580b)

**Comment by git-f0x** [comment]
That's how similar settings are sorted on other desktop environments and operating systems (Windows, macOS, Android,...). The usual expectation is for About/System to be at the bottom, and Networks and Bluetooth at the top.
