### ISSUE TITLE
[Bug] `Install additional languages` doesn't seem to do anything...

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-settings#828]
Maybe I'm missing something, but the `Install additional languages`-button in the `Settings` -> `Time & Language` -> `Add language`-menu doesn't seem to do anything.

![afbeelding](https://github.com/user-attachments/assets/995ca092-4103-4833-beae-6cacf45a61ea)

cosmic-session-git 1.0.0.alpha.4.r2.g0a3b9f5-1

Greetings

**Comment by feikedonia** [comment]
Related to #791

**Comment by mmstick** [comment]
Do you have `gnome-language-selector` installed on the system? That is required for cosmic-settings.

**Comment by feikedonia** [comment]
No I do not, but I can't find it on Arch Linux:

 https://archlinux.org/packages/?sort=&q=gnome+language+selector&maintainer=&flagged=

**Comment by mmstick** [comment]
It's probably under a different package name. It's part of GNOME

**Comment by feikedonia** [comment]
How do I search this package in Arch? Maybe you know the name that Gnome gives it, so I can search in Arch wiki for the Gnome name?

**Comment by CodingKraken** [comment]
I'm not sure why this was marked as complete. Arch doesn't seem to have a `gnome-language-selector` package, and I haven't been able to find an equivalent in the AUR. If anyone has a solution it would be nice if it could be posted here.

**Comment by feikedonia** [comment]
> I'm not sure why this was marked as complete. Arch doesn't seem to have a `gnome-language-selector` package, and I haven't been able to find an equivalent in the AUR. If anyone has a solution it would be nice if it could be posted here.

You are right, but I can't reopen the issue

**Comment by feikedonia** [comment]
The thing is: it dóés work on fedora, (btw)
