### ISSUE TITLE
[Bug] Wi-Fi settings submenu: `Settings`-button doesn't seem to do anything

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-settings#839]
Settings → Network & Wireless → Wi-Fi

under `Known Networks` if you click on the three dots, a menu appears. Click on `Settings`: nothing happens.

cosmic-session-git 1.0.0.alpha.4.r2.g0a3b9f5-1

_`Known Networks`-section_
![afbeelding](https://github.com/user-attachments/assets/944fc4ca-d100-45a9-a7d3-0b6657878658)

_Clicking on `Settings` doesn't do anything_
![afbeelding](https://github.com/user-attachments/assets/b28a95d4-04e0-4971-b422-9d5ca5b8bd19)

**Comment by mmstick** [comment]
nm-connection-editor is a required dependency of cosmic-settings
