### ISSUE TITLE
Settings > Input Devices > Keyboard

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#9]
Keyboard settings in COSMIC is where the user will be able to manage input sources and keyboard shortcuts. 
![keyboard](https://github.com/pop-os/cosmic-settings/assets/57502897/f46076cb-6b8c-449b-836f-a484aab5fb79)

## Input Sources
Users should be able to add Input sources by clicking on "Add input source" button at the bottom of the ListView with input sources. Clicking this button should bring up the ContextDrawer with the list of input sources and a search field to enable people to quickly find what they need. 
![keyboard-add-input-context-drawer](https://github.com/pop-os/cosmic-settings/assets/57502897/781da513-03e6-48b5-843a-1a330b7416fd)

Users should be able to drag Input sources inside the ListView to rearrange them. Each input source should have a View-more icon button at the end of the list item that brings up the menu with options to move the item inside the list, view keyboard layout, removing the input source, and additional settings if they are available. 
![view-more-menu](https://github.com/pop-os/cosmic-settings/assets/57502897/ea6416f1-880a-4981-9efb-f853c2856180)

The copy underneath the heading of the section specifies the keyboard binding for switching input sources. It should change here if one customizes it in keyboard shortcuts. 

When there is more than one input source added Input Sources applet should be added to the Panel (see [Panel configurations designs](https://github.com/pop-os/cosmic-epoch/issues/102)). 

## Special Character Key
Compose key setting is shown in this section. Clicking on the List item with Compose key should open the ContextDrawer with the options to set Compose key to a specific modifier. 

## Keyboard Shortcuts.
Clicking on "View and customize shortcuts" should take the user to the[ Keyboard Shortcuts page](https://github.com/pop-os/cosmic-settings/issues/32).

**Comment by trigg** [comment]
I would love a per-device Input Source.

My laptop keyboard layout is GB, but my mechanical keyboard is US. Switching is an option but it'd be much nicer if it could be set per-device.

**Comment by trigg** [comment]
That explains why it's not a feature I've seen before.

Thanks for explaining that to me!

**Comment by 16hournaps** [comment]
Not sure if this is a known issue or not. 

My custom layout that worked in X11/Wayland on stable PopOS! does not show up in the selector. It is english special layout. I installed it the same way as before (installation guide https://github.com/binarybottle/engram/tree/master/install/linux/x_keyboard_extension).

Maybe its not PopOS!'s issue, but it is a regression from previous version.

**Comment by Leonardoes22** [comment]
> Not sure if this is a known issue or not.
> 
> My custom layout that worked in X11/Wayland on stable PopOS! does not show up in the selector. It is english special layout. I installed it the same way as before (installation guide https://github.com/binarybottle/engram/tree/master/install/linux/x_keyboard_extension).
> 
> Maybe its not PopOS!'s issue, but it is a regression from previous version.

For anyone having the same issue, it seems that cosmic uses `base.xml` instead of `evdev.xml` to get layout information. Copying the custom layout information to `base.xml` fixed it for me.

**Comment by VasilisManol** [comment]
@Leonardoes22 can you please explain in more detail how you fixed this? I want to add the layout "German, Swedish and Finnish (US)", which otherwise appears as input source when selecting "Show extended input sources". I tried to copy 
      ```
<variant>
          <configItem popularity="exotic">
            <name>de_se_fi</name>
            <description>German, Swedish and Finnish (US)</description>
            <languageList>
              <iso639Id>eng</iso639Id>
              <iso639Id>deu</iso639Id>
              <iso639Id>swe</iso639Id>
              <iso639Id>fin</iso639Id>
            </languageList>
          </configItem>
        </variant>
```
in  /usr/share/X11/xkb/rules/base.xml but didn't work.

**Comment by Leonardoes22** [comment]
@VasilisManol in my case I just had to copy the new keyboard to the appropriate file in the `symbols` directory and add the correspoding entry to `base.xml`.

Here is my install script if you want to check exactly what I did: https://github.com/Leonardoes22/US-BR

**Comment by VasilisManol** [comment]
Thanks @Leonardoes22 ! In my case the layout already exists in the base.lst file and evdev.xml but is missing in the base.xml. I think I had missed something in the base.xml file previously. It works now.

**Comment by natecox** [comment]
> Keyboard layout works a bit differently from a technical standpoint. A client is sent a single "keymap" (https://wayland.app/protocols/wayland#wl_keyboard:event:keymap), that probably isn't reasonable to change dynamically depending on what keyboard is used.

Worth noting here that hyprland currently supports dynamic keymapping per input device, though I don't know the implementation details: https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs
