### ISSUE TITLE
Settings > Appearance: Light mode issues

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#90]
- [ ] Light mode activates in the settings app but not the rest of the desktop
- [ ] After choosing light mode, then click "< Desktop", the window reverts to dark mode
- [ ] Light mode active window accent does not change
- [ ] Window management > active window hint size and gap size don't work in the light mode window

**Comment by WatchMkr** [comment]
I'm seeing these issues on one up-to-date computer but not another. Closing for now.

**Comment by wash2** [comment]
Hmm that's strange. I do have a fix for applets not picking up a system theme in libcosmic though. https://github.com/pop-os/libcosmic/pull/202

**Comment by wash2** [comment]
>  After choosing light mode, then click "< Desktop", the window reverts to dark mode

I do remember this being an issue before but I thought I fixed it. I'll keep an eye out for it as well. 

> Light mode active window accent does not change
> active window hint size and gap size don't work in the light mode window

I don't remember seeing these issues but I'll keep an eye out for them as well.
