### ISSUE TITLE
(Settings/Desktop/Appearance)  Colour Picker Does Not Fully Update.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-settings#94]
When using a colour picker spawned by the Appearance settings, switching between theme sections will update the values in the colour picker, save for the 2 dimensional brightness/saturation array.

Here you can see the issue: 

![Screenshot_2023-11-10_15-49-10](https://github.com/pop-os/cosmic-settings/assets/98765732/384e7a5f-f7cc-48f4-91df-e61ac192d8b8)
![Screenshot_2023-11-10_15-49-19](https://github.com/pop-os/cosmic-settings/assets/98765732/e4a311ac-7400-4c40-9594-00921553f7c2)

In the first image, the "Application or window background" value has been selected to edit. 

In the second image, without closing the colour picker, "Interface text tint" was selected. 

The window has updated between the two - the Hex value displayed is correct, and the Hue slider is correctly updated. However the brightness/saturation array still shows the previous "Application or window background" values.

**Comment by XV-02** [comment]
This may also be tied to an issue I'm seeing when picking a colour. If I select withing the brightness/saturation array, it will update the UI elements being tinkered with. If I change the hue with the slider, it doesn't update the UI element until I click into the brightness/saturation array.

**Comment by wash2** [comment]
Thanks I will look into this tomorrow.

**Comment by wash2** [comment]
> This may also be tied to an issue I'm seeing when picking a colour. If I select withing the brightness/saturation array, it will update the UI elements being tinkered with. If I change the hue with the slider, it doesn't update the UI element until I click into the brightness/saturation array.

I'm able to replicate the second issue but not the first issue

**Comment by XV-02** [comment]
The first issue is still present on our currently released packaging... but it's fixed in master! :tada: 

So, at this point, only the second issue persists.
